### ISSUE TITLE
Shared Code Support

### ISSUE THREAD

**Issue by weswitt** [arduino/arduino-cli#100]
I would like to see support for shared code across an Arduino target and another arbitrary target (like some Linux code).

When using a straight makefile based build system I'd use VPATH to facilitate shared code. There is nothing like that available with this CLI tool. The CLI is a great step in the right direction but I need more flexibility. I have some C++ file & headers that I need to share between Arduino code & non-Arduino code.

**Comment by scls19fr** [comment]
I wonder if the concept of environments (#108) couldn't help?
