### ISSUE TITLE
Enabling sketch verification by default

### ISSUE THREAD

**Issue by LumitoLuma** [arduino/arduino-cli#1003]
It would be great if the sketch if verified by default, instead of needing to specify the `-t` flag every time you want to do it. Instead, the `-t` flag can be used to disable the verification, like `-V` in `avrdude`.

Thanks!

**Comment by umbynos** [comment]
The verification unfortunately increases the upload time. On the other hand the failure due to upload errors are so low that this is not worth to be enabled.
