### ISSUE TITLE
[ Nightly Build Regression ] - Arduino CLI will not use the default configuration .yaml file

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-cli#1018]
We recently introduced a regression which ended up in the latest Nightly.

The current Nightly build will not take the config file in consideration, so it won't be possible to search for boards and install them unless you pass in a path to the correct configuration file

the temporary workaround is to add `--config-file` as a flag

In my setup I run
`arduino-cli config dump --config-file $ARDUINO_PREF/arduino-cli.yaml`
`arduino-cli core search samd --config-file $ARDUINO_PREF/arduino-cli.yaml`

We'll be patching this tomorrow, apologies for any inconvenience if you're testing a NIghtly Build.
Reminder: do not use Nightly Builds (or Alpha, for what it's worth) in your production setup :D

thanks
Arduino Tooling Team

**Comment by silvanocerza** [comment]
I think this could be closed, we reverted the culprit commit and refactored how configs are handled to reimplement the wanted features with #1027.
