### ISSUE TITLE
{build.core.path} undefined for Tools / Burn Bootloader

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/arduino-cli#1031]
{build.core.path} is not defined when Tools / Burn Bootloader is executed making it impossible to use a tool included with the core.

**Comment by per1234** [comment]
This is essentially a duplicate of https://github.com/arduino/arduino-cli/issues/1012, but that is about the `upload` action, while this is about the `erase` and `bootloader` actions.

The same applies to the `program` action as well.

**Comment by cmaglie** [comment]
Fixed by #2082
