### ISSUE TITLE
Adding Core Support

### ISSUE THREAD

**Issue by weswitt** [arduino/arduino-cli#106]
Is there some documentation showing how to add support for a new core? Docs for the package json and the layout for the distribution zip file referenced in the json?

**Comment by per1234** [comment]
Here it is:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x-package_index.json-format-specification

And instructions for using 3rd party Boards Manager packages with arduino-cli:
https://github.com/arduino/arduino-cli#adding-3rd-party-cores
