### ISSUE TITLE
Feature Request: report incorrect or malformed values in library.properties

### ISSUE THREAD

**Issue by ianfixes** [arduino/arduino-cli#1094]
## Feature Request

Create what is essentially a linting tool for `library.properties`.  This would catch things like the following:

* the `library.properties` filename is capitalized in an unexpected way (if case-sensitive filesystems would care)
* the file contains binary, or has some other text encoding error
* the file contains unexpected keys
* a key contains an unparseable value
* an expected key was not found

### Example JSON output

```json
{
  "file": {
    "path": "/path/to/Library.PROPerties",
    "issues": [
      {
        "severity": "warning",
        "message": "The library.properties filename should be all lowercase"
      },
      {
        "severity": "error",
        "message": "File contains binary data"
       }
    ]
  },
  "contents": {
    "parsed": {
        /* the parsed contents of the file */
    },
    "issues": [
      {
        "severity": "warning",
        "message": "The 'name' field was not found"
      },
      {
        "severity": "warning",
        "message": "Unexpected field 'potatoes'",
        "line": 4
      },
      {
        "severity": "error",
        "message": "field 'dot_a_linkage' expects a boolean",
        "line": 8
      },
    ]
  }
}
```

Having the line number reported in the output would enable GitHub annotations directly on the affected lines.

**Comment by per1234** [comment]
Thanks @ianfixes. As you noticed, we have now released the Arduino Lint tool which provides this capability and more:
https://blog.arduino.cc/2021/01/13/detect-problems-with-your-arduino-projects/

The only exception is this:
>the file contains unexpected keys

The presence of arbitrary keys in library.properties doesn't cause any problems. People might use these for their own purposes. For example, some library authors began adding a `license` field even though this is not mentioned in the specification. What we do have is a check for potentially misspelled versions of optional key names (e.g., an `architecture` key when no `architectures` key is present).

As part of the Arduino Lint project, the library.properties data format is now defined in a machine readable form as a [JSON schema](https://json-schema.org/):
https://github.com/arduino/arduino-lint/tree/main/etc/schemas
