### ISSUE TITLE
board install command does not return correct data

### ISSUE THREAD

**Issue by hecko** [arduino/arduino-cli#11]
Running `arduino-cli-0.2.0-alpha.preview-osx board install` does not list installed boards (i would assume this command lists FQBNs of all board names from boards.txt files).

**Comment by acidobinario** [comment]
@hecko maybe the command you're looking to execute is `arduino-cli-0.2.0-alpha.preview-osx board listall` ?

**Comment by cmaglie** [comment]
At least `board install` should **install** new boards (but this is already achieved by `core install`).
As said by @acidobinario the command you're looking for is `board listall`.
