### ISSUE TITLE
sketch.always_export_binaries: true CLI config is ignored when compiling via gRPC API

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#1103]
## Bug Report

If I add the following to the CLI config and compile via the gRPC API, the binaries do not end up in the sketch folder.
```yaml
sketch:
  always_export_binaries: true
```

I have to explicitly set it in the code if I want the binary in my sketch folder.
```ts
const compilerReq = new CompileReq();
compilerReq.setExportBinaries(true);
```

### Expected behavior

`sketch.always_export_binaries: true` is not ignored in the CLI config.

### Environment

- CLI version (output of `arduino-cli version`): 0.14.0-rc1
- OS and platform:

**Comment by umbynos** [comment]
Fixed by #1171
