### ISSUE TITLE
Undocumented (but minor) breaking change in 0.14

### ISSUE THREAD

**Issue by obra** [arduino/arduino-cli#1109]
As part of our build system, we were running 'config init' twice on jobs in CI. Arguably this is a bug.

0.14 changed arduino-cli's behavior in such cases.

0.13 silently either ignored the issue or just overwrote the old config.

0.14 fails with the error `Config file already exists, use --overwrite to discard the existing one.`

I don't think this is a -bad- choice, but it was a little surprising to see jobs start failing. 

It'd be wonderful if stuff like this got into the docs, but I do understand if it's just too much of a burden during alpha.

**Comment by silvanocerza** [comment]
Hi @obra, this is my fault I guess, I introduced this behaviour with #957 in September. 

We didn't have the breaking changes policy back then, during the latest release process I tried to document breaking changes introduced before the policy but must have missed some I guess.

I'll edit the `UPGRADING.md` file accordingly.

Thanks for the report!

**Comment by silvanocerza** [comment]
Upgrading documentation has been updated accordingly and just published. I also updated the release changelog.
https://arduino.github.io/arduino-cli/0.14/UPGRADING/#change-behaviour-of-config-file-flag-with-config-commands

Thanks again for the issue, wouldn't have noticed if not for you. :)

**Comment by obra** [comment]
No worries :)  Thanks!
