### ISSUE TITLE
loader choice in preferences.txt is ignored

### ISSUE THREAD

**Issue by banana-string-theory** [arduino/arduino-cli#1112]
### Current behavior

$ arduino-cli board details SparkFun:apollo3:sfe_artemis_nano

It always shows the first .menu.loader.option_* entry listed in boards.txt, despite the environment having been configured to use a different choice (second menu entry) via the IDE. No indication of why the contrary choice is selected, or how it can be corrected, is provided. In my case this rendered the tool completely unable to upload sketches.

### Expected behavior

The tool should reflect the user-selected preference (custom_loader=) in Arduino15/preferences.txt.
The upload command should support a command-line option for explicitly choosing the loader.

### Environment

$ arduino-cli version
arduino-cli alpha Version: 0.14.0 Commit: a86b21d99e2af9e0857da0ce4ab80baf1d3afb55 Date: 

MacOS Big Sur 11.1

### Additional context
n/a

**Comment by per1234** [comment]
Arduino CLI doesn't use preferences.txt. That file is only used by Arduino IDE. So your configuration in preferences.txt has no effect on Arduino CLI.

In Arduino CLI, [custom board options](https://arduino.github.io/arduino-cli/latest/platform-specification/#custom-board-options) such as the one shown in the Arduino IDE's **Tools > Uploader** menu when the "RedBoard Artemis Nano" board is selected are configured via the FQBN. So if you wanted to set the `loader` custom board option to `option_svl`, you would use this FQBN in your Arduino CLI commands: `SparkFun:apollo3:sfe_artemis_nano:loader=option_svl`

There's a more detailed explanation here: https://github.com/arduino/arduino-cli/issues/591

---
Related: https://github.com/arduino/arduino-cli/issues/355
