### ISSUE TITLE
Feature request: option to syntax check a sketch without fully compiling

### ISSUE THREAD

**Issue by ianfixes** [arduino/arduino-cli#1128]
## Feature Request: syntax checking for sketches

It would be helpful to verify that, outside of any platform-specific or library-specific inclusions, a sketch has proper syntax.  The ideal behavior would be to iterate over the full set of files included in the example sketch and perform `gcc -c` on them.

As a bonus, the JSON response from such a command might contain an object whose keys are the files that were found/tested and whose values are an array of compiler warnings (if any).

**Comment by umbynos** [comment]
Hi @ianfixes, unfortunately checking the syntax requires the libs and the cores also. For example, how do you check if `digitalWrite(10, HIGH);` is syntactically correct? You need the core for that. But at this point you are basically doing a full compile.
