### ISSUE TITLE
Unable to set upload speed on NodeMCU

### ISSUE THREAD

**Issue by scottchiefbaker** [arduino/arduino-cli#127]
I'm able to compile and upload sketches to my NodeMCU board just fine. The upload process is pretty slow, as it looks like it defaults to 115200. In the Arduino UI I'm able to set the upload speed to 460800 and upload just fine. Reading #61 it looks like you can specify the upload speed in the `--fqbn` but it doesn't work?

```
arduino-cli upload -p /dev/ttyUSB1 --fqbn esp8266:esp8266:nodemcuv2:UploadSpeed=115200 ~/Arduino/MySketch/
Error: getting build properties for board esp8266:esp8266:nodemcuv2: invalid option 'UploadSpeed'
```

Am I using the option incorrectly? Or is there a better way to do this?

**Comment by per1234** [comment]
ESP8266 recently changed the menu property names, breaking fqbns that were valid in the previous versions of the ESP8266 core. `UploadSpeed` was changed to `baud`.

Reference: https://github.com/esp8266/Arduino/issues/5572
