### ISSUE TITLE
Could not add proxy setting to the configuration file thanks the cli

### ISSUE THREAD

**Issue by fpistm** [arduino/arduino-cli#1273]
## Bug Report

arduino-cli can managed the proxy setting in its configuration file: `arduino-cli.yaml`
Like this:
```
network:
  proxy: http://<login>:<password>@myproxy.ext:port
```

Anyway it seems it does not able to add it thanks the cli only by editing manually the file.

### Current behavior

`arduino-cli config add network.proxy http://<login>:<password>@myproxy.ext:port`

Result to `Settings key doesn't exist`

### Expected behavior

Be able to add the proxy configuration thanks the cli.

### Environment
- CLI version (output of `arduino-cli version`): arduino-cli alpha Version: 0.18.1 Commit: b3cf8e19 Date: 2021-04-13T13:08:30Z
- OS and platform: Linux

### Additional context
In a general way all possible setting keys should be supported thanks `arduino-cli config <set|add> key.name key.value` commands.

Thanks

**Comment by silvanocerza** [comment]
Yep, I forgot to add the `network.proxy` config to the list of valid ones, thanks for the report.

**Comment by fpistm** [comment]
Thank you @silvanocerza

**Comment by silvanocerza** [comment]
:pray: 

This will be available in the next release for sure, no idea when though.
