### ISSUE TITLE
Installing unregistered library

### ISSUE THREAD

**Issue by scls19fr** [arduino/arduino-cli#128]
Hello,

It will be nice if arduino-cli could provide an interface to install unregistered library:

From a zip available on HTTP server:

    arduino-cli lib install --unregistered https://github.com/itead/ITEADLIB_Arduino_Nextion/archive/master.zip

supporting installing from a git repository might also be considered
(by default it could use master branch but we could install from any given branch, or from a given commit hash, or tag)

You might have a look at how Ruby bundler is doing this
https://bundler.io/v1.12/git.html

Kind regards

**Comment by BleuLlama** [comment]
Related; it would be nice to be able to at least use --additional-urls to specify the json files for third party (unregistered) libraries.  (I'd make this another issue/ticket but it seems too related to this one)

**Comment by ubidefeo** [comment]
+1 on this
providing a GitHub URL would be ideal, maybe we don't even need to specify flags

**Comment by asucada** [comment]
I'll work on this.

**Comment by alranel** [comment]
We now have `arduino-cli lib install --git-url <url>` and `arduino-cli lib install --zip-file <url>`. 🎉
