### ISSUE TITLE
Upload tool 'avrdude' not installed

### ISSUE THREAD

**Issue by mrhieu059** [arduino/arduino-cli#131]
I installed avrdude on my Arch Linux but idk why it can not recognize avrdude.
How can I fix it? 
https://i.imgur.com/wMhKuHR.png

**Comment by facchinm** [comment]
Hi @mrhieu059 ,
`arduino-cli` doesn't use system-wide tools but needs its own tools in proper locations (eg. ~/.arduino15`). To make them available you should install the package for avr boards first.

Said that, supporting system-wide tools could be viable with some small changes, if someone is willing to take a look it would be cool :slightly_smiling_face:

**Comment by mrhieu059** [comment]
Hi @facchinm 
Can you give me some idea how to install that package?
I am using Arduino Mega2560 R3
