### ISSUE TITLE
Trying to build the code in Visual Studio Code

### ISSUE THREAD

**Issue by bmitov** [arduino/arduino-cli#1335]
I have cloned the repository under:

```text
C:\arduino-cli GIT\arduino-cli
```

on my Windows system. I have installed GO support in the Visual Studio Code.
I have opened the `main.go` and trying to rebuild. When trying to build getting the following and similar errors:

```
could not import github.com/arduino/arduino-cli/cli (cannot find package \"github.com/arduino/arduino-cli/cli\" in any of \n\tC:\\Program Files\\Go\\src\\github.com\\arduino\\arduino-cli\\cli (from $GOROOT)\n\tC\\src\\github.com\\arduino\\arduino-cli\\cli (from $GOPATH)\n\t\\Users\\mitov\\go\\src\\github.com\\arduino\\arduino-cli\\cli (from $GOPATH))
```

I am new to GO so probably doing something stupid. Any suggestions on what I need to configure to get it to compile? I am trying to debug the bug I reported earlier.
Any help would be appreciated!

**Comment by umbynos** [comment]
Hi @bmitov unfortunately we do not offer specific support for a specific IDE, but [installing Golang](https://go.dev/doc/install) and following [this documentation](https://arduino.github.io/arduino-cli/0.29/CONTRIBUTING/#prerequisites) you should be able to proceed
