### ISSUE TITLE
Detect FQBN automatically when port is supplied to compile/upload

### ISSUE THREAD

**Issue by alranel** [arduino/arduino-cli#1357]
As of now, `compile` and `upload` require the `-b` flag to supply the board FQBN, eg:

```
arduino-cli compile -u -p /dev/cu.usbmodem1D11 -b arduino:avr:mega
```

It would be nice to let users omit `-b` whenever `-p` is supplied:

```
arduino-cli compile -u -p /dev/cu.usbmodem1D11
```

In this case, FQBN can be *tentatively* detected using the same logic we already have for `board list` which provides the port-FQBN mapping.

The advantage of this would be a greatly simplified UX because we would remove the extra step of calling `board list` to read the FQBN (or the need for users to understand/find the correct FQBN manually from other source), thus reducing the needed awareness of the FQBN concept and the cognitive load related to it.

**Comment by rsora** [comment]
Nice enhancement proposal thanks @alranel, just one note to our future self:

the message has to be shown only in "CLI mode" and not in "Daemon mode" so it will require a bit of logic to be implemented correctly.

cc @cmaglie @silvanocerza
