### ISSUE TITLE
Downloading missing tool builtin:mdns-discovery@0.9.2... but SHA@%^ is invalid format?

### ISSUE THREAD

**Issue by Rinksrides2013** [arduino/arduino-cli#1457]
Downloading missing tool builtin:mdns-discovery@0.9.2...
builtin:mdns-discovery@0.9.2 downloaded                                                                                                                   
Installing builtin:mdns-discovery@0.9.2...
Error initializing instance: installing builtin:mdns-discovery@0.9.2 tool: Cannot install tool builtin:mdns-discovery@0.9.2: testing local archive integrity: testing archive checksum: invalid checksum format: SHA-256cc1096936abddb21af23fa10c435e8e9e37ec9df2c3d2c41d265d466b03de0af
Error initializing instance: discovery not installed: builtin:mdns-discovery
Error initializing instance: discovery not installed: builtin:mdns-discovery
Error initializing instance: discovery not installed: builtin:mdns-discovery
Sketch uses 924 bytes (2%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.

Downloading missing tool builtin:mdns-discovery@0.9.2...
builtin:mdns-discovery@0.9.2 downloaded                                                                                                                   
Installing builtin:mdns-discovery@0.9.2...
Error initializing instance: installing builtin:mdns-discovery@0.9.2 tool: Cannot install tool builtin:mdns-discovery@0.9.2: testing local archive integrity: testing archive checksum: invalid checksum format: SHA-256cc1096936abddb21af23fa10c435e8e9e37ec9df2c3d2c41d265d466b03de0af
Error initializing instance: discovery not installed: builtin:mdns-discovery
Error initializing instance: discovery not installed: builtin:mdns-discovery
Error initializing instance: discovery not installed: builtin:mdns-discovery

Is this a bug or feature to see if the pi is connected to the internet?

**Comment by per1234** [comment]
Hi @Rinksrides2013. Thanks for taking the time to submit an issue. This is a bug, which was previously reported at https://github.com/arduino/arduino-cli/issues/1446

This has already been fixed by https://github.com/arduino/arduino-cli/pull/1448 but there hasn't been a release since then.

You can get the fix by using the nightly build of Arduino CLI:
https://arduino.github.io/arduino-cli/0.19/installation/#nightly-builds
