### ISSUE TITLE
Remove hardcoded builtin-tools and move them to package_index.json

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-cli#1485]
At the moment `arduino-cli` installs default tools at first launch

* https://github.com/arduino/arduino-cli/blob/master/commands/bundled_tools_ctags.go
* https://github.com/arduino/arduino-cli/blob/master/commands/bundled_tools_mdns_discovery.go
* https://github.com/arduino/arduino-cli/blob/master/commands/bundled_tools_serial_discovery.go

These should be converted to standalone tools and added to the main `package_index.json` to be downloaded at need

**Comment by silvanocerza** [comment]
PR that updates `package_index.json` created: https://github.com/bcmi-labs/package_index/pull/7

**Comment by silvanocerza** [comment]
Draft PR that removes hardcoded `builtin` package from Arduino CLI created: https://github.com/arduino/arduino-cli/pull/1537
Will be ready for review after bcmi-labs/package_index#7 is merged and a new `package_index.json` is released.
