### ISSUE TITLE
Factor out the arduino-cli `legacy` package

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-cli#1486]
Arduino CLI embeds some legacy code which should be factored out and/or cleaned up.

- provide an initial assessment of the components to delete
- delete and run tests to check for regressions
- build Arduino Builder at every step and add to Java IDE to test for failure
- repeat until all Legacy is removed

**Comment by umbynos** [comment]
This needs to be split in subtasks

**Comment by umbynos** [comment]
Related PRs:

- https://github.com/arduino/arduino-cli/pull/2147
- https://github.com/arduino/arduino-cli/pull/2160
- https://github.com/arduino/arduino-cli/pull/2151
- https://github.com/arduino/arduino-cli/pull/2132
- https://github.com/arduino/arduino-cli/pull/2127
- https://github.com/arduino/arduino-cli/pull/2124
- https://github.com/arduino/arduino-cli/pull/2123
- https://github.com/arduino/arduino-cli/pull/2121
- https://github.com/arduino/arduino-cli/pull/2082
- https://github.com/arduino/arduino-cli/pull/2038

**Comment by umbynos** [comment]
Completed
