### ISSUE TITLE
The `core.GetPlatforms` function ignores the `all` field showing manually installed cores

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-cli#1520]
The `core.GetPlatforms` function is not working as intended right now but the logic of this function is good.
It ignores the `All` field in the rpc.PlatformListRequest showing the manually installed cores even if the `All` field is set to false.
see https://github.com/arduino/arduino-cli/pull/1509#discussion_r730758844

**Comment by 4ntoine** [comment]
Nope, it seems that `all` is [used](https://github.com/arduino/arduino-cli/blob/master/commands/core/list.go#L41) in the code. I will create another ticket for my issue

**Comment by ubidefeo** [comment]
@umbynos @4ntoine 
can we assume this is a closed issue in light of #1521 being merged?

**Comment by umbynos** [comment]
Actually that PR is not merged yet because the tests are not passing. It surely need some more investigation

**Comment by alessio-perugini** [comment]
Fixed in: https://github.com/arduino/arduino-cli/pull/2357
