### ISSUE TITLE
arduino-cli.exe lib install --log-level Debug does not work but is printed in help

### ISSUE THREAD

**Issue by ArminJo** [arduino/arduino-cli#1528]
### Current behavior
`arduino-cli.exe lib install` prints: `--log-level string          Messages with this level and above will be logged. Valid levels are: Trace, Debug, Info, Warning, Error, Fatal, Panic`

But `arduino-cli.exe lib install ServoEasing --log-level Debug` results in: `Invalid option for --log-level: Debug`

Only `arduino-cli.exe lib install ServoEasing --log-level debug`  works 😀.

### Expected behavior
The help printout should be correct even with upper and lowercase!

### Environment

- CLI version (output of `arduino-cli version`): arduino-cli.exe alpha Version: nightly-20211020 Commit: 7b468c0 Date: 2021-10-20T01:28:38Z
- OS and platform: W10

**Comment by umbynos** [comment]
Hi @ArminJo, It seems I cannot reproduce your issue, could you please try with the latest stable? [0.21.1](https://github.com/arduino/arduino-cli/releases/tag/0.21.1)

**Comment by ArminJo** [comment]
Thanks for fixing 👍
