### ISSUE TITLE
`GetPlatform` called via gRPC does not force to update the indices

### ISSUE THREAD

**Issue by 4ntoine** [arduino/arduino-cli#1529]
### Current behavior

Call `GetPlatform` with `all=true` on a clean system does not force to update the indices.

### Expected behavior

It forces the update (exactly as it's done if calling via command-line `core list --all`

### Environment

- CLI version (output of `arduino-cli version`): 0.19.2 commit [6a6f50ae](https://github.com/arduino/arduino-cli/commit/6a6f50ae)
- OS and platform: Alpine linux

### Additional context

Looking into the source code i can't see any difference except missing `instance.CreateAndInit()` [call](https://github.com/arduino/arduino-cli/blob/e0d983a8840f4d2c1024a50a3909f21796458710/cli/core/list.go#L52).

In my case i do call create + init requests before requesting the subscriptions.

PS. Using custom `data` path in config file (not sure if it makes a difference)

**Comment by umbynos** [comment]
`GetPlatform` does not update the index by design. We won't change that.
By the way downloading the indexes during the first start is something that we should implement.
I'm keeping this issue open to track this task.
