### ISSUE TITLE
Tabs not usable as whitespace in platform recipes

### ISSUE THREAD

**Issue by tmxkn1** [arduino/arduino-cli#1532]
The IDE 2.0 fails to compile any code for OpenCM 9.04, even a "blank" code:
```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

```

The error I get is:
```
arm-none-eabi-gcc: error: 	-c: No such file or directory
Compilation error: Error: 2 UNKNOWN: exit status 1

```

IDE version:
```
Version: 2.0.0-beta.3
Date: 2021-02-26T10:47:31.812Z (1 week ago)
CLI Version: 0.16.1 alpha [76f55490]
```

OS:
PC1: Ubuntu 16.04.7 LTS x86064
PC2: Win10 10.0.19042

**Comment by umbynos** [comment]
Using tab separation is not supported by the latest Arduino IDE 1.8.19. Adding this now would bring even more fragmentation. Furthermore, we cannot see a use case for this.
