### ISSUE TITLE
compile sends data to StandardError stream

### ISSUE THREAD

**Issue by HendrikMennen** [arduino/arduino-cli#1554]
I am currently implementing arduino CLI into my own IDE.

For some reason, compiling sends data to standarderror that are not errors (marked in red).
![image](https://user-images.githubusercontent.com/25281882/142482881-6359bf70-16fa-4369-990b-f0a08aefc596.png)

Can someone tell me why this is happening?

**Comment by per1234** [comment]
It is happening because that is what the ESP8266 platform developers wrote their tool to do:

https://github.com/esp8266/Arduino/blob/3.0.2/tools/sizes.py#L83-L85

```python
    sys.stderr.write("Executable segment sizes:" + os.linesep)
    for k in sizes.keys():
        sys.stderr.write("%-7s: %-5d %s %s" % (k, sizes[k], hints[k], os.linesep))
```
