### ISSUE TITLE
Upload command return no result

### ISSUE THREAD

**Issue by lefuturiste** [arduino/arduino-cli#158]
command: `arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:megaADK ~/arduino`
result: `\n`
platform: Raspbian 9.6 stretch ARMv7

I just can't upload my compiled code.

**Comment by per1234** [comment]
Please run this command:
```
arduino-cli upload -p /dev/ttyUSB0 --verbose --fqbn arduino:avr:megaADK ~/arduino
```
and then copy and paste the complete output from the upload here.

**Comment by lefuturiste** [comment]
Ok, in fact I didn't see my arduino blinking so ok you are not telling if the upload operation was successfull.

Great so it's not an issue
