### ISSUE TITLE
`arduino-cli board list --format json` command doesn't return `VID` and `PID` with the `--watch` flag.

### ISSUE THREAD

**Issue by instanceofMA** [arduino/arduino-cli#1609]
Hey, [this PR](https://github.com/arduino/arduino-cli/pull/1076) mentions that the `arduino-cli board list --format json` command returns `VID` and `PID` with the `--watch` flag as well, but I can't make it to return `VID` and `PID`. Is there some other flag for it? Here's how it works for me:

https://user-images.githubusercontent.com/26253942/147410728-c0f7a07f-f930-449d-ba87-0d001bf6e375.mov

_Originally posted by @abdullahmahboob in https://github.com/arduino/arduino-cli/issues/1076#issuecomment-1001188741_

**Comment by silvanocerza** [comment]
You're right, the output from `board list --format json` and `board list --watch --format json` should be identical but it's not.
Thanks for the report, we'll fix this. :pray:

**Comment by per1234** [comment]
Fixed by #1845
