### ISSUE TITLE
Embed settings in the internal CoreInstance

### ISSUE THREAD

**Issue by silvanocerza** [arduino/arduino-cli#1627]
Currently configs used by the Arduino CLI are stored in a global struct, both when running in `daemon` or command line mode.

This behaviour has some issues since it prevents gRPC consumers to use different configs for different clients connected to it, this means that if a client wants to change settings they change for all clients.

The solution is to embed the settings in the `CoreInstance` and access them only through it. This will enhance a lot how settings are handled and also make it easier to write unit tests for certain code parts.

**Comment by silvanocerza** [comment]
Part of this task is already been done on branch `scerza/embedding-settings`.

**Comment by umbynos** [comment]
![image](https://user-images.githubusercontent.com/34278123/216367073-99cef4b6-900f-441c-b478-da11ea29e4f6.png)

Unfortunately this branch is quite old now, we are going for a similar approach in the future maybe.
