### ISSUE TITLE
Command 'arduino.cli' not found

### ISSUE THREAD

**Issue by mianqi2016** [arduino/arduino-cli#1649]
## Bug Report
I want to run arduino-cli in virtualenv on Ubuntu, since it was prompted"ImportError: No module named serial" when I tried to compile an esp32 project in Arduino IDE, I downloaded the tar.gz file, unziped it, and I got 2 files: arduino-cli  and LICENCE.txt, When I typed:"arduino-cli -b esp32:esp32:esp32:PSRAM=enabled,PartitionScheme=huge_app,CPUFreq=80 compile --verbose", it was prompted:"Command 'arduino-cli' not found, but can be installed with:sudo snap install arduino-cli", and the same when I typed:"arduino-cli --version".

### Current behavior

cd /usr/local/bin/arduino-cli
(venv_arduino) mianqi@mianqi-HP-Z228-Microtower-Workstation:/usr/local/bin/arduino-cli$ ls
arduino-cli_0.20.2_Linux_64bit.tar.gz
(venv_arduino) mianqi@mianqi-HP-Z228-Microtower-Workstation:/usr/local/bin/arduino-cli$ sudo tar -xf arduino*
(venv_arduino) mianqi@mianqi-HP-Z228-Microtower-Workstation:/usr/local/bin/arduino-cli$ ls
arduino-cli  arduino-cli_0.20.2_Linux_64bit.tar.gz  LICENSE.txt
(venv_arduino) mianqi@mianqi-HP-Z228-Microtower-Workstation:/usr/local/bin/arduino-cli$ arduino.cli

Command 'arduino.cli' not found, did you mean:
  command 'arduino-cli' from snap arduino-cli (0.20.2)
See 'snap info <snapname>' for additional versions.

### Environment

- CLI version (output of `arduino-cli version`):Command 'arduino.cli' not found
- OS and platform:Ubuntu 20.04

**Comment by per1234** [comment]
Hi @mianqi2016 
>```
>(venv_arduino) mianqi@mianqi-HP-Z228-Microtower-Workstation:/usr/local/bin/arduino-cli$ arduino.cli
>```
The command name is `arduino-cli`, not `arduino.cli` (note **_** vs **.**).

If you don't have `/usr/local/bin/arduino-cli` in your `PATH` environment variable, you will also need to invoke Arduino CLI like this: `./arduino-cli`.
