### ISSUE TITLE
Sketch source move to build folder bug: file extension changing

### ISSUE THREAD

**Issue by VNovytskyi** [arduino/arduino-cli#1699]
### Brief
The problem consists of wrong Arduino CLI builder behaviour. When executing Arduino builder it creates a folder _build/sketch/_ and copies the source files into it. If we change the file extension the builder doesn't remove the old version of the file and still trying to build your application with the old file.

### Steps to reproduce

1. Create a new project with files: `test.ino`, `myLib.h`, `myLib.c`
2. Write wrong code in `myLib.c` to creating the build error
3. Try to build the project
4. Rename `myLib.c` to `myLib.cpp` and fix the build error
5. Try to build the project again

### Current behaviour
Arduino builder tries to build the project with `myLib.c` though `myLib.cpp` is in _build/sketch/_ 

### Expected behaviour
Arduino CLI's builder must detect changing file extension and remove old file myLib.c and use new myLib.cpp

### Command

```text
arduino-cli compile --fqbn esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=fatflash,CPUFreq=240,FlashMode=dio,FlashFreq=80,FlashSize=16M,UploadSpeed=921600,LoopCore=1,EventsCore=1,DebugLevel=debug esp-xmodem-lib-file-test --build-path build --build-cache-path build --port COM11 --upload --export-binaries -v
```

### Environment
- Arduino-cli version: 0.21.1 Commit: 9fcbb392 Date: 2022-02-24T15:41:45Z
- Windows 10 Pro 21H1 19043.1586

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @VNovytskyi.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/1240.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
