### ISSUE TITLE
Works with Windows user, don't works with Windows service

### ISSUE THREAD

**Issue by giesalabs** [arduino/arduino-cli#1719]
### Current behavior

C:\Program Files (x86)\Multi\arduino\arduino-cli.exe" upload -i "C:\Program Files (x86)\Multi\arduino\sketch\extra\Blink-red.ino.hex

You can run arduino-cli with this command from any user on system, but you can't successfully run it from a Windows service.

### Environment

- CLI version: Versione: 0.21.1 Commit: 9fcbb392 Data: 2022-02-24T15:41:45Z
- OS and platform: Windows Server 2016

### Additional context

The reason can be seen quickly, the necessary files are inside AppData\Local and in the case of a Windows Service the folder is located in C:\Windows\System32\config\systemprofile\AppData\Local

by running the installation command "arduino-cli.exe core install arduino:avr" **from service**. 
the compressed files in the Arduino15 folder will be **downloaded**, but they **will not be unzipped**
inside C:\Windows\System32\config\systemprofile\AppData\Local\Arduino15\packages\hardware and tools which remain completely empty (no files)

then launch from Windows service "C:\Program Files (x86)\Multi\arduino\arduino-cli.exe" upload -i "C:\Program Files (x86)\Multi\arduino\sketch\extra\Blink-red.ino.hex" -p COM4 -b arduino:avr:nano
inevitably returns the following error:
Unable to get Documents Folder: The system cannot find the specified file.
time="2022-04-28T19:39:03+02:00" level=error msg="Unable to get Documents Folder: The system cannot find the specified file."
Error during Upload: Platform 'arduino:avr' not found: platform arduino:avr is not installed

The funny thing is that repeating the command "arduino-cli.exe core install arduino:avr" **from service** get: Platform arduino:avr@1.8.5 already installed

While running the command "arduino-cli.exe core list" **from service** returns the following result: Unable to get Documents Folder: The system cannot find the specified file.
time="2022-04-28T19:38:59+02:00" level=error msg="Unable to get Documents Folder: The system cannot find the specified file."

UPDATE:
After trying the command (**from Windows service**) "core install arduino:avr --run-post-install" found in the documentation I see now in C:\Windows\System32\configuration\systemprofile\AppData\Local\Arduino15\packages\arduino the hardware and tools folders with the files inside.
However uploading with the command "C:\Program Files (x86)\Multi\arduino\arduino-cli.exe" upload -i "C:\Program Files (x86)\Multi\arduino\sketch\extra\Blink-red.ino.hex" -p COM4 -b arduino:avr:nano fails with the following message:
Unable to get Documents Folder: The system cannot find the specified file.
time="2022-04-28T21:06:57+02:00" level=error msg="Unable to get Documents Folder: The system cannot find the specified file."
Error while loading: Loading failed: output status 3221225781

**Comment by umbynos** [comment]
Hi @giesalabs, closing for lack of feedback. Feel free to reopen it if you need
