### ISSUE TITLE
Identical description of `listall` and `search` in `arduino-cli board --help` output

### ISSUE THREAD

**Issue by jmnc2** [arduino/arduino-cli#1720]
### Current behavior

arduino-cli board

The help printed:
.
.
  listall     List all known boards and their corresponding FQBN.
  search      List all known boards and their corresponding FQBN.
.
.

But this is more about the getting-started guide.

### Expected behavior

While following: https://arduino.github.io/arduino-cli/0.21/getting-started/
It says:
```if you see an Unknown board listed, uploading should still work as long as you
identify the platform core and use the correct FQBN string. When a board is 
not detected for whatever reason, you can list all the supported boards and
their FQBN strings by running the following:

$ arduino-cli board listall mkr
```

At least for me listall lists the boards that are installed, so just gives a blank list at this point.
After messing around and deleting the settings folder and redoing 
```
$ arduino-cli config init
$ arduino-cli core update-index

```
still the same so after reading help from 'arduino-cli board' tried using: 'arduino-cli board search' instead and that worked.
Then after doing 'arduino-cli core install arduino:avr'
'arduino-cli board listall' now lists all the avr boards supported by arduino:avr

So I guess the documentation is wrong and search is what lists all the boards?
While listall lists the installed boards?

The help from 'arduino-cli board' could also use improving to make it clear what listall and search do.

### Environment

- CLI version (output of `arduino-cli version`):
- OS and platform: Linux Manjaro

**Comment by per1234** [comment]
Thanks @jmnc2! We have an existing issue that is used to track the fact that it is not clear that `board listall` only lists boards of installed platforms: https://github.com/arduino/arduino-cli/issues/550

I think this situation with the command line help produced by `arduino-cli board --help` having identical descriptions for both `listall` and search definitely needs to be fixed, so we can use this issue to track that problem.
