### ISSUE TITLE
Can't list boards on arm

### ISSUE THREAD

**Issue by agdl** [arduino/arduino-cli#1791]
### Describe the problem

Can't list boards on Armbian 21.08.6 Bullseye with Linux 5.10.60-sunxi

launching ```arduino-cli board list```

I get segmentation fault
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8e30]

goroutine 10 [running]:
os.(*Process).signal(0x0, {0xb8e5a8, 0x102018c})
	/usr/local/go/src/os/exec_unix.go:64 +0x38
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:138
os.(*Process).kill(...)
	/usr/local/go/src/os/exec_posix.go:68
os.(*Process).Kill(...)
	/usr/local/go/src/os/exec.go:123
github.com/arduino/arduino-cli/executils.(*Process).Kill(...)
	/home/build/executils/process.go:120
github.com/arduino/arduino-cli/arduino/discovery.(*PluggableDiscovery).killProcess(0x247cdc0)
	/home/build/arduino/discovery/discovery.go:268 +0xdc
github.com/arduino/arduino-cli/arduino/discovery.(*PluggableDiscovery).Quit(0x247cdc0)
	/home/build/arduino/discovery/discovery.go:381 +0x104
github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.(*DiscoveryManager).remove(0x22b0080, {0x94b78e, 0x16})
	/home/build/arduino/discovery/discoverymanager/discoverymanager.go:82 +0x94
github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.(*DiscoveryManager).RunAll.func1(0x247cdc0)
	/home/build/arduino/discovery/discoverymanager/discoverymanager.go:131 +0x78
github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.(*DiscoveryManager).parallelize.func1(0x658e130, 0x6580138, 0x6596680, 0x247cdc0)
	/home/build/arduino/discovery/discoverymanager/discoverymanager.go:101 +0x50
created by github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.(*DiscoveryManager).parallelize
	/home/build/arduino/discovery/discoverymanager/discoverymanager.go:99 +0x1ac
```

### To reproduce

Launch board list on nanopi neo with Armbian 21.08.6 Bullseye with Linux 5.10.60-sunxi

### Expected behavior

Boards should be listed

### Arduino CLI version

 0.24.0 Commit: c1b10f56 Date: 2022-06-22T10:09:11Z

### Operating system

Linux

### Operating system version

Armbian 21.08.6 Bullseye with Linux 5.10.60-sunxi

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @agdl. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/1775.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
