### ISSUE TITLE
Incorrect error `details` when the `LoadSketchRequest` fails with `NOT_FOUND` error

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#1797]
### Describe the problem

If I have such a gRPC `LoadSketchRequest`:

```json
{
    "instance": {
        "id": 1
    },
    "sketchPath": "/Users/a.kitta/Documents/Arduino/alma"
}
```

And the folder is missing from the file system:
```
 % cd ~/Documents/Arduino/alma
cd: no such file or directory: /Users/a.kitta/Documents/Arduino/alma
```

Then the request correctly fails with a [`NOT_FOUND`](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) status code but the error `details` is incorrect:
```json
{
    "code": 5,
    "details": "Can't open sketch: no valid sketch found in /Users/a.kitta/Documents/Arduino: missing /Users/a.kitta/Documents/Arduino/Arduino.ino",
    "metadata": {
        "content-type": [
            "application/grpc"
        ]
    }
}
```

The error message should be about `Arduino/alma/alma.ino` and not `Arduino/Arduino.ino`. The `directories.user` location exists on my disk:
```
% ls -al ~/Documents/Arduino 
total 0
drwxr-xr-x  2 a.kitta  staff   64 Jul  8 16:50 .
drwx------+ 5 a.kitta  staff  160 Jul  6 15:46 ..
```

### To reproduce

 - Get the IDE2 build from here: https://github.com/arduino/arduino-ide/pull/1152
 - Create a new sketch and save it,
 - Quit IDE2,
 - Delete the previously deleted sketch and start IDE2,
 - You will see the incorrect error message

<img width="582" alt="Screen Shot 2022-07-08 at 17 05 58" src="https://user-images.githubusercontent.com/1405703/178019542-20bbe6ca-06af-4721-b70a-5473b510a801.png">

### Expected behavior

It should complain about `~/Documents/Arduino/alma` and not `~/Documents/Arduino/`

### Arduino CLI version

`0.24.0`

### Operating system

macOS

### Operating system version

12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
The issue also occurs with the Arduino CLI command line interface:

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 6ac5f7a3 Date: 2022-07-09T19:16:18Z

$ mkdir /tmp/Arduino

$ arduino-cli compile -b arduino:avr:uno /tmp/Arduino/alma
Error opening sketch: no valid sketch found in C:\Users\per\AppData\Local\Temp\Arduino: missing C:\Users\per\AppData\Local\Temp\Arduino\Arduino.ino

$ arduino-cli compile -b arduino:avr:uno /tmp/Arduino/alma/alma.ino
Error opening sketch: reading files: open C:\Users\per\AppData\Local\Temp\Arduino\alma: The system cannot find the file specified.

$ arduino-cli compile -b arduino:avr:uno /tmp/Arduino/alma/nonexistent
Error opening sketch: reading files: open C:\Users\per\AppData\Local\Temp\Arduino\alma: The system cannot find the file specified.
```

The error message code was written based on the unwarranted assumption that people always provide the full path to the `.ino` file. However, it's faster and more correct (because the folder is the sketch, not the `.ino` file) to only provide the path to the sketch folder.
