### ISSUE TITLE
arm-none-eabi on windows

### ISSUE THREAD

**Issue by djmcgill** [arduino/arduino-cli#18]
```
C:\Users\David>arduino-cli core install arduino:samd
The tool arduino:arm-none-eabi-gcc@4.8.3-2014q1 is not available for the current OS
```
How does the regular IDE install arm-none-eabi-gcc?

As a workaround, I think that the cli should look in `AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\` (or at least some user-specified directory) because that contains windows executables for the arm-none-eabi toolchain.

**Comment by cmaglie** [comment]
This should be solved in the next alpha release of the CLI.
