### ISSUE TITLE
Cannot compile sketch containing invisible characters

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#1808]
### Describe the problem

Sketch compilation fails if the sketch contains invisible characters. I do not know if it's a builder, preprocessor, or pure C++ issue.

### To reproduce

```cpp
void setup() {
  char s = 'x' ;
}
void loop() {}
```

Note that after the `'x'` there is an invisible character.
<img width="304" alt="Screen Shot 2022-07-19 at 11 37 51" src="https://user-images.githubusercontent.com/1405703/179721036-80db7fa0-948e-43fc-8f37-34425d292f74.png">
<img width="668" alt="Screen Shot 2022-07-19 at 11 37 30" src="https://user-images.githubusercontent.com/1405703/179721042-0baf048b-aee9-41b9-9c2c-f6a20de23cb8.png">

Compilation:
```
a.kitta@Akoss-MacBook-Pro sketch_jul18b % ~/dev/git/arduino-ide/arduino-ide-extension/build/arduino-cli version
arduino-cli  Version: 0.25.0-rc1 Commit: 63b53c0f Date: 2022-07-11T16:09:52Z
a.kitta@Akoss-MacBook-Pro sketch_jul18b % cat ~/Documents/Arduino/sketch_jul18b/sketch_jul18b.ino 
void setup() {
  char s = 'x' ;
}
void loop() {}
a.kitta@Akoss-MacBook-Pro sketch_jul18b % ~/dev/git/arduino-ide/arduino-ide-extension/build/arduino-cli compile -b arduino:samd:mkr1000 ~/Documents/Arduino/sketch_jul18b 
/Users/a.kitta/Documents/Arduino/sketch_jul18b/sketch_jul18b.ino:2:15: error: stray '\302' in program
   char s = 'x'��;
               ^
/Users/a.kitta/Documents/Arduino/sketch_jul18b/sketch_jul18b.ino:2:16: error: stray '\240' in program
   char s = 'x'��;
                ^



Used platform Version Path                                                                  
arduino:samd  1.8.13  /Users/a.kitta/Library/Arduino15/packages/arduino/hardware/samd/1.8.13

Error during build: exit status 1
```

### Expected behavior

If it's possible to compile a `cpp` file that contains the `<0xa0>` invisible character, I would expect to work with the CLI too.

### Arduino CLI version

arduino-cli  Version: 0.25.0-rc1 Commit: 63b53c0f Date: 2022-07-11T16:09:52Z

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

Based initially on https://github.com/arduino/arduino-ide/issues/1210.
Possibly related (based on the compiler error message): https://github.com/arduino/arduino-cli/issues/1785

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by matthijskooijman** [comment]
Looks like an error thrown by `gcc`. I am pretty (but not 100%) sure that including such characters (at least outside of a string constant) produces an invalid C++ file, so gcc is correct to complain. I'm going to go ahead and closes this for not being an actual bug.

One could argue that there is a bug where these invisible characters should be more prominently displayed somehow, but that would need to reported in another repository (and I think this is unlikely to be fixed in 1.x, and I suspect your last screenshot is from 2.x, so it would already be reasonably handled there?).
