### ISSUE TITLE
BSD version

### ISSUE THREAD

**Issue by LudwikZimmenhof** [arduino/arduino-cli#1815]
### Describe the request

Good morning, can you make a BSD build? I've tried to build it myself (I did everything alright) but it failed while Go was downloading packages.

### Describe the current behavior

There is no BSD binary and you can't compile it yourself because Go has problem with downloading packages for it.

### Arduino CLI version

0.25

### Operating system

N/A

### Operating system version

FreeBSD 13.1, OpenBSD 7.1

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by cmaglie** [comment]
Should be fixed by https://github.com/arduino/arduino-cli/pull/2116, please re-open with more details if the issue still exists.
