### ISSUE TITLE
user: Current not implemented on linux/arm

### ISSUE THREAD

**Issue by Renaud11232** [arduino/arduino-cli#182]
When the program is run without the `USER` environment variable set, it shows : 
```
./arduino-cli board listall
Error: getting default arduino data dir: retrieving user home dir: user: Current not implemented on linux/arm
Error creating default configuration
```
This can happen for instance, when `arduino-cli` is used by a program launched using `start-stop-daemon` on boot with `/etc/init.d/something`

Here is the debug output:
```
./arduino-cli board listall --debug
ERRO[0000] Error creating default configuration          error="getting default arduino data dir: retrieving user home dir: user: Current not implemented on linux/arm"
ERRO[0000] Error creating default configuration          error="getting default arduino data dir: retrieving user home dir: user: Current not implemented on linux/arm"
Error: getting default arduino data dir: retrieving user home dir: user: Current not implemented on linux/arm
Error creating default configuration
```

It fails with the other commands as well.

To reproduce the issue simply do : 
```bash
unset USER
./arduino-cli board listall
```

According to [this issue](https://github.com/golang/go/issues/14625) `cgo` might be missing.

**Comment by SConaway** [comment]
If you're here for docker, run `export USER=root` on ubuntu.

**Comment by masci** [comment]
Fixed in https://github.com/arduino/arduino-cli/pull/239
