### ISSUE TITLE
An other preprocessing bug (probably).

### ISSUE THREAD

**Issue by jfjlaros** [arduino/arduino-cli#1822]
### Describe the problem

A sketch containing a function that makes use of a type created with `typedef` does not compile under certain circumstances. This issue may be related to bug #1785.

### To reproduce

When the following sketch is compiled,

```cpp
void somefunction() {}
typedef int myInt;
void myTest(myInt) {}

void setup() {}
void loop() {}
```

this error is raised:

```txt
.../x.ino:3:18: error: variable or field 'myTest' declared void
 void myTest(myInt) {}
                  ^
.../x.ino:3:13: error: 'myInt' was not declared in this scope
 void myTest(myInt) {}
             ^~~~~
```

When the first two lines are swapped, the sketch compiles fine.

```cpp
typedef int myInt;
void somefunction() {}
// ...
```

### Expected behavior

Both sketches are expected to compile. For reference, the following code compiles without any errors or warnings

```cpp
void somefunction() {}
typedef int myInt;
void myTest(myInt) {}

int main() {
  return 0;
}
```

with the following command:

```bash
g++ -std=c++11 -Wall -Wextra -pedantic x.cc
```

### Arduino CLI version

nightly-20220803 Commit: 2dd8976 Date: 2022-08-03T01:36:48Z

### Operating system

Linux

### Operating system version

Debian bookworm/sid

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @jfjlaros. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/1269.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
