### ISSUE TITLE
Support core version list

### ISSUE THREAD

**Issue by dilin-MS** [arduino/arduino-cli#183]
Hi, @cmaglie, 

Does arduino-cli support `core version list`? Scenario is that user want to install some core of a specific version instead of the latest one, eg. `esp8266@2.4.2`. Does arduino-cli support listing all available versions of a certain core? For example, list out all versions of esp8266, and user can decide which version to install.

This need can be met when using the Arduino IDE. On the Board Manager, user is able to use the drop-down menu to choose a certain version of board to download. 

Thanks!

**Comment by shade34321** [comment]
I'm not sure what needs to be done with this one but I wouldn't mind trying this one if that's ok.
