### ISSUE TITLE
List All Libraries

### ISSUE THREAD

**Issue by dilin-MS** [arduino/arduino-cli#185]
Hi @cmaglie ,

Can arduino-cli support listing all available libraries? Like you select the "all" type in Arduino IDE's Library Manager. Currently we can only use `arduino-cli lib search XXX` to search some libraries related to one core. Cases are that I have a device A, and want to use libraries from other core, like Arduino or something. Listing all available libraries can give information to user so he can check the library.

Thx.

**Comment by ololosha228** [comment]
i think, this is not neccessary, but it can be easily implemented. can you write some cases, how to use it?

**Comment by ololosha228** [comment]
it works like you say:
```
$ arduino-cli lib search
Name: "I2C Temperature Sensors derived from the LM75"
  Author:  Jeremy Cole <jeremy@jcole.us>, Liam Cole <liam@liamiam.com>
  Maintainer:  Jeremy Cole <jeremy@jcole.us>
...
```

try it! :full_moon_with_face:

**Comment by dilin-MS** [comment]
Thanks! That's what I need. :)
