### ISSUE TITLE
`Error loading hardware platform (ESP8266)` error when installing mbed Portenta core

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-cli#1864]
### Describe the problem

When installing the `mbed_portenta` core, an error message is displated regarding the ESP8266 having `malformed custom board options`. Does not noticablely affect the operation with a Portenta board otherwise.

### To reproduce

1. Open Windows PowerShell (non-adminsistrator)
2. Provide permissions for the Scoop installer ` Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser` 
3. Install the latest arduino IDE via scoop `scoop install arduino-cli` (in this case, 0.27.0)
4. Update the CLI index then install the `mbed_portenta` core ` arduino-cli core install arduino:mbed_portenta`
5. The following message is displayed
```
Downloading missing tool builtin:mdns-discovery@1.0.6...
builtin:mdns-discovery@1.0.6 downloaded
Installing builtin:mdns-discovery@1.0.6...
builtin:mdns-discovery@1.0.6 installed
Error initializing instance: Error loading hardware platform: loading platform release esp8266:esp8266@2.7.1: loading boards: skipping loading of boards esp8266:esp8266:espduino: malformed custom board options
Error initializing instance: Error loading hardware platform: loading platform release esp8266:esp8266@2.7.1: loading boards: skipping loading of boards esp8266:esp8266:espduino: malformed custom board options
```

### Expected behavior

No messages about the ESP8266 would show up. 

### Arduino CLI version

0.27.0

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @aliphys. As reported by Arduino CLI, there is a problem with the version of the ESP8266 boards platform you have installed.

That problem was fixed last year, so you must have an outdated version of the platform installed on your computer:

https://github.com/esp8266/Arduino/pull/8153

You will no longer get the error if you update to `esp8266:esp8266@3.0.2`
