### ISSUE TITLE
Can Not Build QueueHandle_t of FreeRTOS

### ISSUE THREAD

**Issue by mamoru1126** [arduino/arduino-cli#1920]
### Describe the problem

Hello, 
I created a program used message queues of FreeRTOS for M5stack gray.
An example program is as follows:

```cpp
#include "M5Stack.h"
QueueHandle_t test;
void function(void){
  test = xQueueCreate(4, sizeof(DATA_SET) );
}
void setup(){}
void loop(){}
```

I built this program using the following command:

```text
arduino-cli compile --fqbn esp32:esp32:m5stack-core-esp32 test.ino
```

Then the following error message was output

![image](https://user-images.githubusercontent.com/58585300/195640572-93bc53d7-a39e-4ceb-a1df-dfd4470db0e7.png)

Please let me know how to resolve this error.

### To reproduce

Create a program using `QueueHandle_t` and Build it using arduino-cli

### Expected behavior

Error message is output

### Arduino CLI version

0.27.1

### Operating system

Linux

### Operating system version

ubuntu 20.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @mamoru1126. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
