### ISSUE TITLE
[doc] locale is missing from the CLI config spec

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#1928]
### Describe the problem

`locale` is a valid CLI config entry, but it's undocumented yet. https://arduino.github.io/arduino-cli/0.27/configuration/#configuration-keys

### To reproduce

Go to https://arduino.github.io/arduino-cli/0.27/configuration/#configuration-keys, `locale` is not there.

### Expected behavior

`locale` is documented

### Arduino CLI version

It's not a CLI malfunction

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Beyond a documentation deficiency, the configuration key is not even supported by the `arduino-cli config` command:

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 54a0bc07 Date: 2022-10-18T10:28:55Z

$ arduino-cli config set locale de
Settings key doesn't exist
```

I think that bug should be fixed before or during the documentation update since the user will expect to have full functionality from any documented configuration key.
