### ISSUE TITLE
[Question] How do you install this on the raspberry pi?

### ISSUE THREAD

**Issue by NovaViper** [arduino/arduino-cli#194]
I'm trying to install this library in order to use the Marlin Firmware flash plugin for Octoprint.

**Comment by per1234** [comment]
1. Go to the "Releases" page of this repository: https://github.com/arduino/arduino-cli/releases
2. From the "Assets" list, click on the link that has "linuxarm" in the filename.
3. Wait for the download to finish.
4. Extract the downloaded file.

You can copy the extracted file to any convenient location on your drive. There is no additional installation required.

This issue tracker is intended to be used for reporting bugs and making feature requests. In the future, please ask this type of question on the [Arduino Forum](http://forum.arduino.cc/). I'm sure we'll be able to help you out over there.

**Comment by NovaViper** [comment]
How do I download the file on the Pi though? I don't have the desktop installed (only the command line)

**Comment by per1234** [comment]
Use wget:
https://www.gnu.org/software/wget/
