### ISSUE TITLE
Variable {runtime.hardware.path} not evaluated on board in sketchbook

### ISSUE THREAD

**Issue by grzybsonssg** [arduino/arduino-cli#1971]
### Describe the problem

Hi
I have issue with 3rd party board installed through the sketchbook (user folder).
Variable `{runtime.hardware.path}` is not properly evaluated, whereas other variables are replaced with proper values.
`{runtime.hardware.path}` is global variable that should by evaluated always, right?

### To reproduce

Just try to install Roger Clark's STM32 board following his instruction.
https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation

Compilation of sketch goes without any problem, but it fails on upload due to inability to evaluate variable.
![obraz](https://user-images.githubusercontent.com/45419916/201210051-26930f79-7573-40fd-afc9-86fa444ebefe.png)

Of course I can replace the variable placeholder with absolute path in `platform.txt` and then it runs flawlessly. But that's a hack.

Full verbose output of compile and upload in attachment.

[arduino_stm32_output.txt](https://github.com/arduino/arduino-ide/files/9984741/arduino_stm32_output.txt)

### Expected behavior

`{runtime.hardware.path}` is properly evaluated to `c:\users\grzybson\Documents\Arduino\hardware\Arduino_STM32\`

### Arduino IDE version

2.01

### Operating system

Windows

### Operating system version

10 Pro 22H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for your report @grzybsonssg. In case it will be useful for the preparation and validation of a fix, I'll provide a minimal demonstration of the bug:

I created a minimal boards platform that uses a [build hook](https://arduino.github.io/arduino-cli/dev/platform-specification/#pre-and-post-build-hooks-since-arduino-ide-165) to print `{runtime.platform.path}` to the verbose console output during the compilation action, and the upload pattern to print it during the upload action: [foo.zip](https://github.com/arduino/arduino-cli/files/9987156/foo.zip)


```text
$ arduino-cli version

arduino-cli  Version: nightly-20221111 Commit: 79e6484 Date: 2022-11-11T01:35:52Z

$ export ARDUINO_DIRECTORIES_USER="/tmp/arduino-cli-directories/user"

$ mkdir --parents "$ARDUINO_DIRECTORIES_USER/hardware"

$ wget --output-document="$ARDUINO_DIRECTORIES_USER/hardware/foo.zip" https://github.com/arduino/arduino-cli/files/9987156/foo.zip

[...]

$ unzip "$ARDUINO_DIRECTORIES_USER/hardware/foo.zip" -d "$ARDUINO_DIRECTORIES_USER/hardware"  # Install the demo platform

Archive:  /tmp/arduino-cli-directories/user/hardware/foo.zip
   creating: /tmp/arduino-cli-directories/user/hardware/foo/
   creating: /tmp/arduino-cli-directories/user/hardware/foo/avr/
  inflating: /tmp/arduino-cli-directories/user/hardware/foo/avr/boards.txt  
  inflating: /tmp/arduino-cli-directories/user/hardware/foo/avr/platform.txt  

$ arduino-cli core update-index

Downloading index: package_index.tar.bz2 downloaded 

$ arduino-cli core install arduino:avr  # Install dependency of the demo platform

[...]

$ arduino-cli sketch new "$ARDUINO_DIRECTORIES_USER/Qux"

$ arduino-cli compile --fqbn foo:avr:bar --upload --verbose "$ARDUINO_DIRECTORIES_USER/Qux"

[...]
echo /tmp/arduino-cli-directories/user/hardware/foo
/tmp/arduino-cli-directories/user/hardware/foo
[...]
echo {runtime.hardware.path}
{runtime.hardware.path}
[...]
```

🐛 The `{runtime.hardware.path}` property reference was not expanded in the upload pattern.

The property reference is expanded as expected in the upload pattern when using Arduino IDE 1.8.19:

```text
echo /tmp/arduino-cli-directories/user/hardware/foo
/tmp/arduino-cli-directories/user/hardware/foo
```
