### ISSUE TITLE
Please update package index spec for all published architectures 

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/arduino-cli#2004]
### Describe the request

Fully document the recognized values for the `packages[*].tools[*].systems[*].host` field of the package index.

### Describe the current behavior

Currently [Arduino CLI Download](https://arduino.github.io/arduino-cli/0.29/installation/#download) has 9 platforms (assuming Windows exe & msi 64 bit are the same) but only 6 are documented in the [Package Index Specification](https://arduino.github.io/arduino-cli/0.29/package_index_json-specification/#tools-definitions).

![screenshot](https://user-images.githubusercontent.com/965463/206167684-d58d7682-fb68-4958-a3b3-6f7322921512.png)

### Arduino CLI version

271d241e13b63c014383af5d6eec270ad512ce03

### Operating system

N/A

### Operating system version

N/A

#### Additional reports

- https://github.com/arduino/arduino-cli/issues/1168
- https://github.com/espressif/arduino-esp32/issues/7729#issuecomment-1396156190
- https://github.com/arduino/arduino-ide/issues/666#issuecomment-1031346845
- https://forum.arduino.cc/t/file-permissions-of-custom-board-packages/946382/3

#### Related

- https://github.com/arduino/arduino-cli/issues/1917
- https://github.com/arduino/arduino-cli/issues/1838

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
This was previously requested at https://github.com/arduino/arduino-cli/issues/1168

My reply there provides more information about the subject: https://github.com/arduino/arduino-cli/issues/1168#issuecomment-773297581

Even though the requester closed the issue after that reply, I did not consider or intend that response to resolve the request. I am not happy with the current documentation of `packages[*].tools[*].systems[*].host` in the Arduino Package Index Specification and would like to find a way to improve it.

**Comment by cmaglie** [comment]
Here a possible fix https://github.com/arduino/arduino-cli/pull/2260
