### ISSUE TITLE
Arduino Uploading Error - Newbie, please help!

### ISSUE THREAD

**Issue by vaiidy** [arduino/arduino-cli#2032]
### Describe the problem

Hello there, so currently im building my own streamdeck and I've never ever had anything in my life to do with coding or codes so I am very new to this but wanted to put myself through the challenge. My Code seems to work and not give me any error messages. (Code for Additional Hotkeys) but I CONSTANTLY and always no matter what code I try to use or apply get this Error message: 

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44
i've barely seen anyone on the internet having the same issue, and those that have I haven't really found a awnser that explained to me well enough what to do to fix this issue so that i can upload my code to my Arduino Micro Chip. that's the board i'm using right now. Also there are 2 constant glowing red lights and one green light, idk if that means anything aswell. Any help with my journey would greatly be appreciated!

### To reproduce

This is my code I currently have:

#include "Keyboard.h"

const int f13_pin = 3;
const int f14_pin = 4;
const int f15_pin = 5;
const int f16_pin = 6;
const int f17_pin = 7;
const int f18_pin = 8;
const int f19_pin = 9;
const int f20_pin = 10;

void setup() {
  pinMode(f13_pin, INPUT_PULLUP);
  pinMode(f14_pin, INPUT_PULLUP);
  pinMode(f15_pin, INPUT_PULLUP);
  pinMode(f16_pin, INPUT_PULLUP);
  pinMode(f17_pin, INPUT_PULLUP);
  pinMode(f18_pin, INPUT_PULLUP);
  pinMode(f19_pin, INPUT_PULLUP);
  pinMode(f20_pin, INPUT_PULLUP);

  Keyboard.begin();
}

void loop() {
  if (digitalRead(f13_pin) == LOW) {
    Keyboard.press(KEY_F13);
    delay(100);
    Keyboard.release(KEY_F13);
  }
  if (digitalRead(f14_pin) == LOW) {
    Keyboard.press(KEY_F14);
    delay(100);
    Keyboard.release(KEY_F14);
  }
  if (digitalRead(f15_pin) == LOW) {
    Keyboard.press(KEY_F15);
    delay(100);
    Keyboard.release(KEY_F15);
  }
  if (digitalRead(f16_pin) == LOW) {
    Keyboard.press(KEY_F16);
    delay(100);
    Keyboard.release(KEY_F16);
  }
  if (digitalRead(f17_pin) == LOW) {
    Keyboard.press(KEY_F17);
    delay(100);
    Keyboard.release(KEY_F17);
  }
  if (digitalRead(f18_pin) == LOW) {
    Keyboard.press(KEY_F18);
    delay(100);
    Keyboard.release(KEY_F18);
  }
  if (digitalRead(f19_pin) == LOW) {
    Keyboard.press(KEY_F19);
    delay(100);
    Keyboard.release(KEY_F19);
  }
  if (digitalRead(f20_pin) == LOW) {
    Keyboard.press(KEY_F20);
    delay(100);
    Keyboard.release(KEY_F20);
  }
}

### Expected behavior

I would expect my code to be uploaded to my chip so that when I press my self-built stream deck button it can be used as a new Hotkey in for example Stream labs or OBS 

### Arduino CLI version

Arduino IDE 2.0.3

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @vaiidy. I have explained the situation in a reply to your Arduino Forum post about the same:

https://forum.arduino.cc/t/arduino-constant-uploading-error/1075137
