### ISSUE TITLE
grpc empty object when updating the library index 

### ISSUE THREAD

**Issue by Bikappa** [arduino/arduino-cli#2046]
### Describe the problem

When using an grpclient to update the library index, command `UpdateLibrariesIndex`, the download process is ended by and empty object following the "end" message

### To reproduce

Start the CLI in deamon mode
```
arduino-cli daemon
```
Create an instance (here using the `grpcurl` tool)
```shell
grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create
```
Issue an  `UpdateLibrariesIndex` command
```shell
grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.UpdateLibrariesIndex
 ```
 You should observe an output similar to the following
 ```json
{
  "downloadProgress": {
    "start": {
      "url": "https://downloads.arduino.cc/libraries/library_index.tar.bz2",
      "label": "Downloading index: library_index.tar.bz2"
    }
  }
}
{
  "downloadProgress": {
    "update": {
      "downloaded": "2358123",
      "totalSize": "2358123"
    }
  }
}
{
  "downloadProgress": {
    "end": {
      "success": true
    }
  }
}
{

}
 ```
 Notice how there's an empty `{}` object at the bottom

### Expected behavior

The message
```json
{
  "downloadProgress": {
    "end": {
      "success": true
    }
  }
}
```
Closes the stream with no additional objects

### Arduino CLI version

commit a58d5ad

### Operating system

macOS

### Operating system version

13.1 (22C65)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by cmaglie** [comment]
I think it's due to this line:

https://github.com/arduino/arduino-cli/blob/4b70e0238bbd022697404124f10e111d90171a11/commands/daemon/daemon.go#L165

just returning `nil` instead of an empty response should be fine.
I guess there are other "streaming" calls that have the same problem.
