### ISSUE TITLE
Wrong error messages capitalization

### ISSUE THREAD

**Issue by Bikappa** [arduino/arduino-cli#2047]
### Describe the problem

The error message prompted when listing libraries of a missing platform has wrong capitalization
The error message in terminal should use lower case letters: "error": "Error listing Libraries: Unknown FQBN: platform arduino:samd is not installed" should be "error": "Error listing libraries: Unknown FQBN: platform arduino:samd is not installed"

### To reproduce

Make sure the candidate platform, `samd` in the example, is not installed
One option is to remove them all
```
rm -rf ~/Library/Arduino15
```
Issue a command to list the libraries of a board
```
arduino-cli lib list --fqbn arduino:samd:xyz
```
Observe the error message with weird capitalization
```
Error listing Libraries: Unknown FQBN: platform arduino:samd is not installed
```

### Expected behavior

The error message should be
```
Error listing libraries: Unknown FQBN: platform arduino:samd is not installed
```

### Arduino CLI version

git commit a58d5ad

### Operating system

MacOS

### Operating system version

13.1 (22C65)

### Additional context

Possibly other messages should be checked and eventually improved

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by cushonz** [comment]
[https://github.com/arduino/arduino-cli/pull/2048](Fixed with fix 2048, awaiting pull)
