### ISSUE TITLE
Documentation issue with core install command

### ISSUE THREAD

**Issue by jeff-winn** [arduino/arduino-cli#205]
The core install documentation that is displayed within the console displays conflicting information when attempting to install a specific version.

>  \# download a specific version (in this case 1.6.9).
>  arduino-cli.exe core install arduino:samd=1.6.9

In the above documentation that shows when core install is used, the documentation indicates to use =1.6.9 whereas the command actually needs @1.6.9. This difference can be misleading as executing the command with =1.6.9 ends up displaying an error about a particular version not being found.

**Comment by masci** [comment]
Fixed in #238
