### ISSUE TITLE
The supported file extensions of additional code files are not in sync with the spec

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#2050]
### Describe the problem

Originally from [here](https://github.com/arduino/arduino-ide/pull/1821#issuecomment-1400031873):

> I have noticed that the spec, IDE2 code, and the CLI are not in sync regarding the allowed code file extensions:
> 
> * Spec: https://arduino.github.io/arduino-cli/dev/sketch-specification/#additional-code-files
> * IDE2: https://github.com/arduino/arduino-ide/blob/6140ae525c57f99878e8fcd39727c1966ecf6a84/arduino-ide-extension/src/common/protocol/sketches-service.ts#L175-L179
> * CLI: https://github.com/arduino/arduino-cli/blob/a58d5adbe269ecc55778c007dc8ac39ffd42ce85/arduino/globals/globals.go#L31-L58

### To reproduce

Check the CLI code, the IDE2 code, and the spec: they are three different things.

### Expected behavior

The code follows the spec, or the spec should be updated

### Arduino CLI version

a58d5ad

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
The missing file extensions supported by Arduino CLI should be added to the specification:

- `.hpp`
- `.hh`

The tool versions that support these extensions should also be documented there.

---

Support for all file extensions listed in the specification should be added to Arduino IDE 2.x.
