### ISSUE TITLE
Automate license headers handling / add checks in CI to enforce it

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-cli#2165]
### Describe the request

There are some tools to automate license headers insertion:

https://github.com/google/addlicense
https://github.com/bugst/licenser
...

we may consider creating a Taskfile task to run one of those (or even another one) to automate the creation of license headers in source code. This will ensure that the correct header is used, and updated, across the codebase.

A CI job to check that the correct license headers are present may be added later.

### Describe the current behavior

There are no checks, new file should be manually handled/checked.

### Arduino CLI version

N/A

### Operating system

N/A

### Operating system version

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by umbynos** [comment]
Problaby needs also a modification here https://github.com/arduino/tooling-project-assets/tree/main/workflow-templates
