### ISSUE TITLE
Unnecessary auto-search for port

### ISSUE THREAD

**Issue by LloydMilligan** [arduino/arduino-cli#2166]
IDE 2.1.0 Teensy Loader 1.58.  Port is selected from Teensy ports group. Loader reports using 'auto-search to find board' and requests to select port, which was already selected using Ports(Teensy). Image capture: https://www.lloydm.net/Images/Annotated_port_warning.jpg

**Comment by per1234** [comment]
Hi @LloydMilligan. Thanks for taking the time to submit an issue.

This [**Teensy Loader**](https://www.pjrc.com/teensy/loader.html) tool used by [the Teensy boards platform](https://www.pjrc.com/arduino-ide-2-0-0-teensy-support/) is not maintained by Arduino so I think the report is off topic here.

I suggest you report this on the **PJRC (Teensy) Forum**:

https://forum.pjrc.com/forum.php

If any defects or deficiencies in the [Arduino boards platform framework](https://arduino.github.io/arduino-cli/dev/platform-specification/) or [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) (which handles the boards platforms for Arduino IDE 2.x) are identified through that discussion, you are welcome to submit bug reports or feature requests  for them here.
