### ISSUE TITLE
Out of Memory error and process killed while Installing esp32 core in EC2 Instance (Free Tier Ubuntu)

### ISSUE THREAD

**Issue by DevsBotIOT** [arduino/arduino-cli#2175]
### Describe the problem

I was trying to install esp32 core arduino-cli in EC2 Free (t1.micro Instance). By using this https://lindevs.com/install-arduino-cli-on-ubuntu I have installed Arduino-cli. After that I issued the below commands.

arduino-cli config init
sudo nano /home/ubuntu/.arduino15/arduino-cli.yaml          (updated additional-urls ["https://espressif.github.io/arduino-esp32/package_esp32_index.json"])
arduino-cli core update-index --config-file .arduino15/arduino-cli.yaml 
arduino-cli config dump   =[shows additional-urls esp32 link]      
arduino-cli core install esp32:esp32

At the last command, starting seems to be running smooth and at the final esp32 installation it hangs for few minutes and got a message killed and the installation stops. I tried many times and same result. I Checked the /var/log/kern.log and I found this

/var/log/kern.log
May  9 10:06:53 ip-172-31-5-99 kernel: [7260893.611782] Out of memory: Killed process 402210 (arduino-cli) total-vm:1399256kB, anon-rss:682408kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1448kB oom_score_adj:0

### To reproduce

arduino-cli config init
sudo nano /home/ubuntu/.arduino15/arduino-cli.yaml          (updated additional-urls ["https://espressif.github.io/arduino-esp32/package_esp32_index.json"])
arduino-cli core update-index --config-file .arduino15/arduino-cli.yaml 
arduino-cli config dump   =[shows additional-urls esp32 link]      
arduino-cli core install esp32:esp32

### Expected behavior

esp32 core must be installed after the command.

### Arduino CLI version

0.32.2

### Operating system

Linux

### Operating system version

22.04.01

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by umbynos** [comment]
Hi @DevsBotIOT, this seems related to #1568 and #1059. And the high memory usage should be solved by #981. To me it seems that you are trying to install a [3rd party core](https://github.com/espressif/arduino-esp32) to a [low resource system](https://instances.vantage.sh/aws/ec2/t1.micro). Unfortunately I think there is nothing we can do.. But I can suggest to upgrade to an ec2 instance with more RAM
