### ISSUE TITLE
Attiny167 1MHz internal Clock not working on baud rate 9600

### ISSUE THREAD

**Issue by sscodecontrol** [arduino/arduino-cli#22]
hello
I am using Attiny167 with arduino uno as a programmer.
I am using 1Mhz internal clock. 
when I set baud rate 9600 in program Serial.begin(9600);  on serial terminal I can not get exact value as i write
for Example :  Serial.write(0xAB); but on terminal m getting : 6B 2B 

But on terminal instead of 9600 if i give 9200 baud rate the i get exact AB AB values.

Can you please help me with this?
I need 9600 baud rate.

Thanks in advance.

**Comment by cmaglie** [comment]
I guess you're on the wrong repository this is about Arduino CLI.
