### ISSUE TITLE
Is it possible to program stm32f103 or stm32f401using UARTor STLink v.2 through the adruino command line?

### ISSUE THREAD

**Issue by brightproject** [arduino/arduino-cli#2205]
### Describe the problem

Is it possible to program stm32f103 or stm32f401using UARTor STLink v.2 through the adruino command line?
Or does the arduino-cli not allow flashing blue and black pills not for USB?
After running example command:
arduino-cli compile -b Arduino_STM32-master:STM32F1:genericSTM32F103C
I got files:
```
.ino.bin
and
.ino.elf
```
in TEMP folder not project folder with source *ino file.
What could be the problem?

Arduino-cli board list - empty
![Скриншот 06-06-2023 17 02 25](https://github.com/arduino/arduino-cli/assets/1788098/53a3f5aa-4890-4227-a512-337bcc267b4f)
### To reproduce

Installed arduino cli via exe file.
Use by powershell.
I used to compile sketches through arduino ide.
Now I want to increase the compilation speed.
but as far as I understand, arduino cli can flash blue and black tablets only via USB
I used stm core from ST [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32)

### Expected behavior

I need upload my code to stm32f401 by STLink from nameScetch.ino by using arduino-cli .

### Arduino CLI version

0.33.0

### Operating system

Windows

### Operating system version

10 Pro

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @brightproject. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for discussion on Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
