### ISSUE TITLE
Compiling without a sketch

### ISSUE THREAD

**Issue by f4lkensmaz3** [arduino/arduino-cli#2208]
### Describe the request

When I try to compile a .ino file in arduino-cli it gives this error,
```
$ arduino-cli compile --fqbn arduino:avr:uno test.ino

Error opening sketch: main file missing from sketch: /home/user/env/env.ino // "env" is the current folder
```
What I would like to suggest is that when the arduino-cli detects the .ino extension in the argument, it should compile right away without checking for the sketch.

If this gets approval, I'll start coding.

### Describe the current behavior

Simply explained in Describe part

### Arduino CLI version

nightly-20230609

### Operating system

Linux

### Operating system version

Artix

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by ubidefeo** [comment]
@f4lkensmaz3 

This is a common misconception, which we have been trying to address multiple times.
As stated in the [sketch specs documentation](https://arduino.github.io/arduino-cli/0.33/sketch-specification/#sketch-root-folder)

> Because many Arduino sketches only contain a single .ino file, it's easy to think of that file as the sketch. However, it is the folder that is the sketch. The reason is that sketches may consist of multiple code files and the folder is what groups those files into a single program.

This means that the sketch is a folder, not the `.ino` file which contains its main entry point.
If you are in a location containing said `.ino` file you just need to issue a `compile` command, and the CLI will look at its path, identify the `cwd` and look for a file named exactly the same with the extension `.ino`

If you are in a directory above such sketch folder, you'll just need to specify the directory name

#### inside the sketch folder
`arduino-cli compile --fqbn arduino:avr:uno`

#### outside sketch folder
`arduino-cli compile --fqbn arduino:avr:uno PATH/TO/mySketch`

Hope this helps :)
