### ISSUE TITLE
Can't install to arduino mega 2560 using arduino-cli, but can using IDE

### ISSUE THREAD

**Issue by j-d-salinger** [arduino/arduino-cli#2230]
### Describe the problem

I have a MKS GEN L v1.0 3dprinter board that works fine uploading using the IDE. But I need to install to it using the arduino-cli.

For some reason, the command arduino-cli board list says that the board has an unknown FQBN. Which is fine, I guess. I guess I don't know how to compile & upload without the FQBN.

The options I need selected (which work in the IDE) are:

Board: Arduino/Genuino Mega or Mega 2560
Processor: ATmega2560
Programmer: AVRISP mkII
I don't understand why these options aren't clearly available in the arduino-cli.

### To reproduce

Try to install to MKS GEN L v1.0 using arduino-cli

### Expected behavior

It to upload

### Arduino CLI version

0.33.0

### Operating system

Linux

### Operating system version

Bullseye debian

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by j-d-salinger** [comment]
I ran these commands: `arduino-cli core install arduino:avr and arduino-cli core install arduino:megaavr`

I ran ` arduino-cli board list`. It says /dev/ttyUSB0, serial, Serial Port (USB), "Unknown" for FQBN....

I run `arduino-cli compile Marlin`. It says "unknown FQBN".

So how do I install using the same parameters in the IDE?

**Comment by per1234** [comment]
Hi @j-d-salinger. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
