### ISSUE TITLE
pico2040w bluetooth problem

### ISSUE THREAD

**Issue by crouse12** [arduino/arduino-cli#2241]
### Describe the request

If you want upload pico2040w bluetooth program to pico 2040w board, ENABLE_CLASSIC should be 1. This parameter can be set if you use arduino ide. Do I know how to set it when I use arduino-cli?

![image](https://github.com/arduino/arduino-cli/assets/25700616/116b4e68-a8b0-4ec4-8381-527bac4fc7c3)

### Describe the current behavior

arduino-cli error message
![image](https://github.com/arduino/arduino-cli/assets/25700616/02e0bfdc-9667-49e3-8c0d-a370abf20925)

### Arduino CLI version

all versions

### Operating system

Windows

### Operating system version

Win11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by umbynos** [comment]
Hello @crouse12, You can use the [`board-options` flag](https://arduino.github.io/arduino-cli/0.33/commands/arduino-cli_compile/#options) for that. You can find more on that [here](https://arduino.github.io/arduino-cli/0.33/platform-specification/#custom-board-options). Something like this should work:
`arduino-cli compile --fqbn rp2040:rp2040:arduino_nano_connect --board-options ipbtstack=ipv4btcble BTSerialUppercase`
