### ISSUE TITLE
source files with space in name breaks install.sh

### ISSUE THREAD

**Issue by henriksod** [arduino/arduino-cli#2243]
### Describe the problem

https://github.com/arduino/arduino-cli/blob/master/legacy/builder/test/sketch_with_config/src/includes/de%20bug.cpp
https://github.com/arduino/arduino-cli/blob/master/legacy/builder/test/sketch_with_config/src/includes/de%20bug.h

The following filenames breaks my build when running install.sh.

I am trying to install arduino-cli in a bazel environment using sh_binary rule.

```
link or target filename contains space on line 1222: 'balancing_robot/external/com_github_arduino_arduino_cli/legacy/builder/test/sketch_with_config/src/includes/de bug.cpp /home/henrik/.cache/bazel/_bazel_henrik/30c47f5a3d285140f3fa83b1f6b1c678/external/com_github_arduino_arduino_cli/legacy/builder/test/sketch_with_config/src/includes/de bug.cpp'
```

### To reproduce

Project setup:

```
# WORKSPACE

workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# arduino-cli
http_archive(
    name = "com_github_arduino_arduino_cli",
    build_file = "//bazel/arduino:arduino_cli.bazel",
    sha256 = "ef9a39fc965e99410e2825211f95836dab9f1f6028dc35f1178a148a42cf8836",
    strip_prefix = "arduino-cli-0.33.1",
    url = "https://github.com/arduino/arduino-cli/archive/refs/tags/0.33.1.tar.gz",
)
```

```
# bazel/arduino/arduino_cli.bazel

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "arduino_cli_install",
    srcs = ["install.sh"],
    data = [":all_srcs"],
)
```

### Expected behavior

No file should have a space in them, since this will break commands.

### Arduino CLI version

df12786440c1078957734aa1686a38c86afcda84

### Operating system

Linux

### Operating system version

Ubuntu 22.04 LTS

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @henriksod. Thanks for your report.

The presence of files with spaces in their filename in this repository is not a defect.

The defect is that Bazel is apparently incapable of dealing with valid and commonly occurring filenames. That defect is tracked here: https://github.com/bazelbuild/bazel/issues/4327

So I close this as off-topic.
