### ISSUE TITLE
Identify final board port address in machine readable `upload` command response

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-cli#2245]
### Describe the request

In some cases, it is possible that the address of the board's port is different at the end of an `upload` operation. Arduino CLI should identify the final address of the target board's port and provide this information in the machine readable `upload` command responses:

- [Response of the `cc.arduino.cli.commands.v1.ArduinoCoreService.Upload` method](https://arduino.github.io/arduino-cli/dev/rpc/commands/#uploadresponse)
- Command line output when non-`text` [format](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli/#options) is specified

🙂 This information will be useful to consumers of Arduino CLI such as development tools and scripts.

### Describe the current behavior

A common scenario under which the port address can change through an `upload` operation is uploading to a "native USB" board, where the primary microcontroller produces the [USB CDC](https://en.wikipedia.org/wiki/USB_communications_device_class) serial port. The typical upload procedure for these boards:

1. Arduino CLI [signals](https://arduino.github.io/arduino-cli/dev/platform-specification/#1200-bps-bootloader-reset) to the target board that it should activate the bootloader.
1. The board switches from application into bootloader mode, which causes its CDC serial port to disappear for a short time.
1. Arduino CLI watches for a new port to be [discovered](https://arduino.github.io/arduino-cli/dev/platform-specification/#pluggable-discovery).
1. Arduino CLI determines the port to use for the upload and provides it for use in [the upload pattern](https://arduino.github.io/arduino-cli/dev/platform-specification/#tools) via [the `upload.port.address` property](https://arduino.github.io/arduino-cli/dev/platform-specification/#serial-port).
   - If a new port was discovered, that port is used.
   - If [the timeout](https://github.com/arduino/arduino-cli/blob/df12786440c1078957734aa1686a38c86afcda84/arduino/serialutils/serialutils.go#L153) was reached without a new discovery, the original port is used as a fallback.
1. Arduino CLI invokes the upload command.
1. The board switches from bootloader to application mode, which causes its CDC serial port to disappear for a short time.

The port address may change following steps (2) and (6) in the above procedure. A system has already been implemented for Arduino CLI to effectively follow the address change after step (2), but there is no such following of the port after step (6). The reason for this is that, unlike the address change at step (2), Arduino CLI itself doesn't have a need to know the final address.

🙁 A final address identification system (which is fairly complex) must be implemented separately in each of the tools that do need this information.

### Arduino CLI version

df12786440c1078957734aa1686a38c86afcda84

### Operating system

All

### Operating system version

Any

### Additional context

This is somewhat related to https://github.com/arduino/arduino-ide/issues/1319 in that it would enable the complete removal of automatic port selection code from the Arduino IDE codebase rather than only the partial removal that is required for the resolution of https://github.com/arduino/arduino-ide/issues/1319.

Examples of tools not correctly determining the final port address:

- https://github.com/arduino/arduino-ide/issues/1648
- https://github.com/arduino/arduino-ide/issues/1366
- https://github.com/arduino/arduino-ide/issues/710
- https://github.com/arduino/arduino-ide/issues/287
- https://github.com/arduino/arduino-ide/issues/82
- https://github.com/arduino/arduino-ide/issues/43

These issues highlight the value of maintaining a single reliable final port identification system instead of duplicating the effort of implementing the system in each individual downstream project.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
Once the feature is available and the CLI can provide the new port (if it has changed) after the upload, I propose eliminating the `hardwareId` from the gRPC API before the 1.0 release. I do not see why this should be exposed to the public. See the downstream change at https://github.com/arduino/arduino-ide/pull/1913:

From [here](https://github.com/arduino/arduino-ide/pull/1913#issuecomment-1653105390):

> This PR has been created to support the "auto-reconnecting" to a board in DFU mode, which the R4 Minima goes into during upload and reset. The primary motivation was to make IDE2 compatible with the Uno R4 board.

Related API:

https://github.com/arduino/arduino-cli/blob/62bb4c47cb2bb64f642cba050a958f45902202ee/rpc/cc/arduino/cli/commands/v1/port.proto#L34-L35

I can open a separate issue if it's needed.
