### ISSUE TITLE
arduino-cli monitor does not flush characters until \n is typed

### ISSUE THREAD

**Issue by cshamis** [arduino/arduino-cli#2251]
### Describe the problem

I was trying to debug my Serial.read() routines and couldn't figure out what I was doing wrong.  None of my keypresses were getting through to my program.  Then I hit enter ... and they ALL came through.  

After much reading about line endings in the terminal (not applicable here) I tried using screen to directly connect to the serial port.  Screen sends the characters as they are typed, and my program works fine.  

Is the arduino-cli monitor buffering until a newline intentional?  Or a bug?  Or just not well documented?  Or... maybe something else.

### To reproduce

void hardwareUART() {
    int charIn = Serial.read();
    if (charIn == -1) {
      return;
    }
   Serial.print(charIn);
  }

### Expected behavior

When typing in a bidirectional terminal, characters are sent as typed.  Not buffered until newline.

### Arduino CLI version

0.33.1

### Operating system

macOS

### Operating system version

Ventura 13.4

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by cmaglie** [comment]
Turns out to be quite challenging to get out of this "line buffering" mode, because it's something that is enforced at the terminal level.

I tried a possible solution here: https://github.com/arduino/arduino-cli/pull/2291 I tested it on Linux but it should work as well on MacOS. Don't know if it works on Windows at all...
