### ISSUE TITLE
Monitor: show timestamp when receiving messages

### ISSUE THREAD

**Issue by alessio-perugini** [arduino/arduino-cli#2316]
### Describe the request

When opening the serial monitor with `arduino-cli monitor -p /dev/ttyACM0` would be cool to prefix the timestamp of a message received from the serial.
We can add a new flag like `--show-timestamp` that enables such a feature.

Expected output:
```bash
[2023-09-13 16:55:22] Message from serial
[2023-09-13 16:55:25] another message
[2023-09-13 16:55:30] a
[2023-09-13 16:55:35] bcd
```

### Describe the current behavior

When we receive a message from the serial monitor we just show them without prefixing the timestamp.

### Arduino CLI version

-

### Operating system

Linux

### Operating system version

Ubuntu 23.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by zvonler** [comment]
Just pushed a commit that I believe resolves this issue. This is my first time writing any Go code (except for the sample program I used to work this out), so please check it carefully and let me know what can be better.

The intent is to print a timestamp before the first character of each line. Any characters received without an included newline are still echoed to the output immediately, and only the first character received after each newline will cause the timestamp output.

I tested with this sketch:
```
void setup()
{
    Serial.begin(115200);
}

static const uint32_t period = 100; // millis

void loop()
{
    static uint32_t last_print_tm = 0;
    static uint8_t next_ch = 0;
    static const char* message = "tick\n";
    if (millis() - last_print_tm > period) {
        Serial.print(message[next_ch++]);
        if (message[next_ch] == '\0')
            next_ch = 0;
        last_print_tm += period;
    }
    delay(10);
}
```

And the runs without and with the new option look like this:
```
Zacharys-iMac:arduino-cli zvonler$ ./arduino-cli -b adafruit:avr:metro monitor -p /dev/cu.usbserial-015F62D6 -c baudrate=115200 --quiet
tick
tick
tick
tick
ti^C
Zacharys-iMac:arduino-cli zvonler$ ./arduino-cli -b adafruit:avr:metro monitor -p /dev/cu.usbserial-015F62D6 -c baudrate=115200 --quiet --timestamp
[2023-09-22 12:12:18] tick
[2023-09-22 12:12:19] tick
[2023-09-22 12:12:19] tick
[2023-09-22 12:12:20] tick
[2023-09-22 12:12:20] tic^C
Zacharys-iMac:arduino-cli zvonler$ 
```
