### ISSUE TITLE
Release Arduino CLI with `v` prefix

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-cli#2341]
We're using some packages of the arduino-cli in other projects. Like fw-uploader plugins, arduino-create-agent and more.
When you don't tag with the v prefix golang treat that tag as it's a pseudo-version and import like: `github.com/arduino/arduino-cli v0.0.0-20230529151818-ca60d4b47be4`
More info here: https://go.dev/ref/mod#versions

**Comment by alessio-perugini** [comment]
One gotcha we have to think of:
- IDE2 assumes no v prefix. (We have to coordinate with them).
- We have to investigate if our tools published in the packing index without the `v` prefix still work or if we need to add the `v` prefix in the index as well.

**Comment by umbynos** [comment]
We have also to verify this will continue to work https://github.com/Homebrew/homebrew-core/blob/e866529e869478aac95e975dad21991c7dd2912e/Formula/a/arduino-cli.rb
