### ISSUE TITLE
Missing `STM32:stm32` platform when using `core install`

### ISSUE THREAD

**Issue by syheliel** [arduino/arduino-cli#2358]
### Describe the problem

`I'm trying to compile the source code in https://github.com/RiS3-Lab/p2im-real_firmware/tree/master/Gateway, it involves the following code:
```
../deps/arduino-cli/arduino-cli compile -b STM32:stm32:Nucleo_64:pnum=NUCLEO_F103RB,upload_method=MassStorage,usb=none,opt=ogstd *.ino --build-path `realpath ./build` -o firmware
```
Then I know that I should install `STM32:stm32`, but it failed:
```
> arduino-cli core install STM32:stm32
Invalid argument passed: Found 0 platform for reference "STM32:stm32":
```
I checked my index through `arduino-cli core list --all`, I ensure that there are some other stuff except for `STM32:stm32`.

### To reproduce

```
        wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz -O "arduino-cli.tar.gz"
        tar xf arduino-cli.tar.gz
        rm arduino-cli.tar.gz
        rm LICENSE.txt
        arduino-cli core update-index
        arduino-cli core install STM32:stm32
```

### Expected behavior

run this cmd successfully:
```
../deps/arduino-cli/arduino-cli compile -b STM32:stm32:Nucleo_64:pnum=NUCLEO_F103RB,upload_method=MassStorage,usb=none,opt=ogstd *.ino --build-path `realpath ./build` -o firmware
```

### Arduino CLI version

arduino-cli  Version: 0.34.2 Commit: 963c1a76 Date: 2023-09-11T10:05:42Z

### Operating system

Linux

### Operating system version

ubuntu22 in Docker

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @syheliel. You can learn how to install 3rd party boards platforms like `STM32:stm32` by reading this section of the documentation:

https://arduino.github.io/arduino-cli/latest/getting-started/#adding-3rd-party-cores

If you have any additional questions or problems using Arduino CLI, please post on Arduino Forum, where we have a dedicated category just for that purpose:

https://forum.arduino.cc/c/software/arduino-cli/89

I'm sure we'll be able to help you out over there.
