### ISSUE TITLE
Does it support using a custom linker script through the command line?

### ISSUE THREAD

**Issue by Slidecarefully** [arduino/arduino-cli#2461]
### Describe the request

I would like to ask if Arduino CLI supports using parameters in the command line and then calling my own custom linker script (i.e., linkerscript.ld file)?

### Describe the current behavior

I haven't tried it yet

### Arduino CLI version

the lateset

### Operating system

Windows, Linux

### Operating system version

win10 or unbuntu 22.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Slidecarefully. Thanks for your interest in this open source project. I see you also asked about this over on Arduino Forum, where I have responded:

https://forum.arduino.cc/t/does-it-support-using-a-custom-linker-script-through-the-command-line/1199591

This issue tracker is only to be used to report bugs or feature requests specific to the Arduino CLI project so the forum will be the most appropriate place for this type of discussion. So I'll go ahead and close this.
