### ISSUE TITLE
Missing tool:- builtin:ctags@5.8-arduino11

### ISSUE THREAD

**Issue by animeshitsme** [arduino/arduino-cli#25]
Does anyone have this tool:- builtin:ctags@5.8-arduino11.
While using arduino cli on my Windows I was able to create sketch but after that when I tried to compile it gives me an error as shown below.
I am not getting that anywhere on the internet or wasn't able to find it.
So it will be very generous of you all if you could provide me that tool.
I will try to manually put it in Arduino15 so that I can compile my code using Arduino-cli.
Thank you in advance.
![screenshot_8](https://user-images.githubusercontent.com/42804463/44790983-3c622100-abbe-11e8-8cf9-738ce921ed98.png)

**Comment by manuel-covas** [comment]
Did you manage to add it manually? I have the same issue but I'm trying to get the cli to run in termux on arm64 Android.
Managed to build from source after bypassing OS name checks.

**Comment by DMaisterra** [comment]
> Did you manage to add it manually? I have the same issue but I'm trying to get the cli to run in termux on arm64 Android. Managed to build from source after bypassing OS name checks.

oh men.... you can do a tutorial in this facts, you made it. or in case to bring any help. looking to make the same. would be good starting from thereq
