### ISSUE TITLE
Load a JSON from local storage

### ISSUE THREAD

**Issue by pillo79** [arduino/arduino-cli#2529]
### Describe the request

I would like to be able to load a package JSON file (possibily with its matching signature!) from a local path and not an URL. This would be really helpful to CI jobs for testing JSON files before public release. 
In this context, it would also be helpful to have the cli load _only_ the specified file, ignoring any default index. 

### Describe the current behavior

`--additional-urls` can be used to fetch data from extra JSONs in most cli commands. However, arguments which are not URLs have no effect. Also, there is no way to avoid loading the default index contents AFAICS.

A current dirty "workaround" is to initialize the cli, then replace `~/.arduino15/package_index.json` with the desidered file contents.

### Arduino CLI version

0.35.2

### Operating system

Linux

### Operating system version

--

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @pillo79.

> I would like to be able to load a package JSON file (possibily with its matching signature!) from a local path and not an URL.

You can do this by using the `file` scheme in the URL.

> Also, there is no way to avoid loading the default index contents AFAICS.

I concur. You are welcome to open a dedicated feature request issue if you think this would be useful.
