### ISSUE TITLE
Manual install library location

### ISSUE THREAD

**Issue by andrethomas** [arduino/arduino-cli#26]
Hi,

Where can I put library folders which I need to install manually?

I'm using the esp8266 compiler/linker

Thanks

**Comment by cmaglie** [comment]
Put them in a directory `libraries` inside your sketchbook folder.
You can identify your sketchbook folder by running:

```
$ arduino-cli config dump
proxy_type: auto
sketchbook_path: /home/cmaglie/Workspace/sketchbook-cores-beta            <---------
arduino_data: /home/cmaglie/.arduino15
```

**Comment by andrethomas** [comment]
Cool, thx in my case its /home/username/Arduino/
