### ISSUE TITLE
Link to OSX latest alpha broken

### ISSUE THREAD

**Issue by ayushpahwa** [arduino/arduino-cli#260]
### Current behavior
https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-osx.zip
link in the readme shows file not found

### Environment

- CLI version (output of `ardunio-cli version`):
- Go version (if building from sources):
- OS version:

**Comment by per1234** [comment]
I have submitted a pull request to fix this:
https://github.com/arduino/arduino-cli/pull/259

The working link is:
https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-macosx.zip
