### ISSUE TITLE
The `config dump` commands doesn't print default values

### ISSUE THREAD

**Issue by alessio-perugini** [arduino/arduino-cli#2637]
### Describe the problem

We have received a PR in https://github.com/arduino/arduino-language-server/pull/188 that wanted to address a nil pointer problem.
After a further investigation, we found out that the `arduino-cli 1.0.0` introduced a regression.

The config dump only prints values present in the `arduino-cli.yaml`.

Here the diff: https://github.com/arduino/arduino-language-server/pull/188#issuecomment-2167487056

### To reproduce

`arduino-cli config dump --json` with the 1.0.0 release

### Expected behavior

It should also print the default values for keys that are not present in the config file

### Arduino CLI version

1.0.0

### Operating system

Linux

### Operating system version

23.10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

**Comment by cmaglie** [comment]
This is the desired behavior, you can use `config get ....` if you need a specific value.

I've pushed a fix in the language server repo https://github.com/arduino/arduino-language-server/pull/189
