### ISSUE TITLE
国外文凭办理精英国际文凭俱乐部www.diplomaclub.net

### ISSUE THREAD

**Issue by dferteyfbxcrterg** [arduino/arduino-cli#266]
### Environment

- CLI version (output of `arduino-cli version`):
- Go version (if building from sources):
- OS version:

### Additional context

[国外文凭办理](www.diplomaclub.net)精英国际文凭俱乐部[www.diplomaclub.net](www.diplomaclub.net)

**Comment by per1234** [comment]
Closing as spam and I have reported @dferteyfbxcrterg to GitHub for abuse.
