### ISSUE TITLE
IDE 2 doesn't handle some file name changes well

### ISSUE THREAD

**Issue by PickyBiker** [arduino/arduino-cli#2680]
### Describe the problem

My sketch had 3 files: stepClass.h, stepClass.cpp and T4DualStep.ino. It was compiling okay. Changed the class file names to stepperClass.h and stepperClass.cpp, and also changed the #include in the .cpp file to the new name stepperClass.h

The IDE started reporting errors that were in the old file name stepClass.cpp which is still in the temp folder, even though there is no reference to that file anywhere in the scketch.

Details of this error and the sketch can be found here: https://forum.arduino.cc/t/code-compiles-in-old-ide-but-not-the-new-one/1286767

It is 100% repeatable

### To reproduce

Use a PC, Tensy 4.0, IDE 2.3.2, and the sketch supplied in the origibl post. . Compile it and make certain the .cpp file has an error somewhere.  Now rename the .cpp, .h, and the #include names. Correct the error in the new .cpp file and compile. This will reproduce the error. rename the temp file with the old name to .cpp.old. Compilation will once again succeed. 

### Expected behavior

Do not expect to see an error.

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

win 11

### Additional context

no additional details

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @PickyBiker. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/1240.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
