### ISSUE TITLE
[Feature Request] snap (Linux package)

### ISSUE THREAD

**Issue by mikeroyal** [arduino/arduino-cli#270]
I was wondering if you might have an interest in a [snap](https://snapcraft.io/) version. I would help make the snap and submit a PR if there's any interest.
[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

**Comment by gvarisco** [comment]
This is something we have been discussing internally (cc @mastrolinux @endorama) and definitely worth exploring. Would you mind submitting a PR for it? We're happy to give it a try!

**Comment by endorama** [comment]
Hi @mikeroyal, I'm very interested in a snap, tag me in the PR so that I can have a look and review it :)

What type of [confinement](https://docs.snapcraft.io/snap-confinement) do you plan to set if the snap?

**Comment by mikeroyal** [comment]
Hi @gvarisco and @endorama, I'll start working on it this weekend.

**Comment by masci** [comment]
PR is here https://github.com/arduino/arduino-cli/pull/281

**Comment by umbynos** [comment]
https://github.com/arduino/arduino-cli/pull/281#issuecomment-1209195561
