### ISSUE TITLE
Arduino IDE hangs on "Downloading index: package_esp32_dev_index.json"

### ISSUE THREAD

**Issue by petrisz** [arduino/arduino-cli#2734]
### Describe the problem

Upon launching the Arduino IDE it begins downloading a package index but it never completes. (I left it to it for 6+ hours and nothing changed). While the editor itself is being responsive, I cannot compile or upload code on my device because the package index download just blocks any other background jobs.

```Downloading index: package_esp32_dev_index.json```

I've checked whether the URL the IDE is trying to access is valid and I could download the same json file manually just fine.

I tried both the latest stable app image (v2.3.3) and the nightly build (20241015), both produce the same (lack of) results.

Please find attached stdout and stderr. [arduino-ide.log](https://github.com/user-attachments/files/17401315/arduino-ide.log)

### To reproduce

Launch the Arduino IDE and wait.

### Expected behavior

1. Successful completion of whatever background process the IDE is trying to run.
2. Ability to run other background jobs like compiling and uploading my sketch.

### Arduino CLI version

1.0.4

### Operating system

Linux

### Operating system version

Linux 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [x] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [x] My report contains all necessary details

**Comment by per1234** [comment]
Hi @petrisz. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/2719.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
