### ISSUE TITLE
[Feature request] include in homebrew/linuxbrew (OSX/Linux)

### ISSUE THREAD

**Issue by endorama** [arduino/arduino-cli#275]
Would be nice to have the cli released through homebrew/linuxbrew also.

**Comment by Efrat19** [comment]
Coming soon... 🤞 
https://github.com/Homebrew/homebrew-core/pull/44575

**Comment by Efrat19** [comment]
Coming soon... 🤞

**Comment by endorama** [comment]
@Efrat19 thank you! I've just installed it, and everything went perfectly on Linux. 

@gvarisco can you please give it a go under MacOSX?

**Comment by gvarisco** [comment]
As a reference, PR for arduino-cli inclusion in homebrew is https://github.com/Homebrew/homebrew-core/pull/44948 and got merged in https://github.com/Homebrew/homebrew-core/commit/cdf88f38253db3a05a4c6ef2f075a53a6c1d04d6

Will let you know once I run a couple of tests.

**Comment by dawidd6** [comment]
Could someone confirm that running `brew test arduino-cli` does not produce an exception on macOS?

Running this command on linux results in an exeception as `arduino-cli` writes the new sketch in `~/Arduino/test_sketch` and in the formula test definition it is actually `~/Documents/Arduino/test_sketch` ($HOME is set to testpath during test).

**Comment by Efrat19** [comment]
@dawidd6  as far as I saw this was fixed at arduino-cli0.5.0-showports, but you preferred not to use that version because it was a pre-release

**Comment by dawidd6** [comment]
@Efrat19 I see, thanks. Actually I was in favor of this `-showports` release, but anyway I workarounded it on linux for now.

**Comment by masci** [comment]
Closing as fixed by https://formulae.brew.sh/formula/arduino-cli
