### ISSUE TITLE
Can't compile for Nano

### ISSUE THREAD

**Issue by nkieffer** [arduino/arduino-cli#29]
Unable to compile for Nano. The arduino:avr core is installed. I've been able to compile for other boards included in the arduino:avr core.
<code><pre>
nkieffer@cmis-nkieffer ~/Arduino $ arduino-cli core list
ID         	Installed	Latest	Name              
arduino:avr	1.6.21   	1.6.21	Arduino AVR Boards

nkieffer@cmis-nkieffer ~/Arduino $ arduino-cli compile --fqbn arduino:avr:nano Sweep/
avr-g++: error: missing device or architecture after '-mmcu='
Error: exit status 1
Compilation failed.

nkieffer@cmis-nkieffer ~/Arduino $ arduino-cli compile --fqbn arduino:avr:uno Sweep
Build options changed, rebuilding all
Alternatives for Servo.h: [Servo@1.1.2]
ResolveLibrary(Servo.h)
  -> candidates: [Servo@1.1.2]
Sketch uses 2158 bytes (6%) of program storage space. Maximum is 32256 bytes.
Global variables use 52 bytes (2%) of dynamic memory, leaving 1996 bytes for local variables. Maximum is 2048 bytes.

</pre></code>

**Comment by tab4moji** [comment]
for the new bootliader, the fqbn is "arduino:avr:nano:cpu=atmega328".
but I dont know the option for the old bootloader.

**Comment by nkieffer** [comment]
Using arduino:avr:nano:cpu=atmega328 as the fqbn worked for me.

**Comment by cmaglie** [comment]
Duplicate of #23

**Comment by scottchiefbaker** [comment]
I came to create a new issue about the Nano with the "old" bootloader and found it here. Thank you!

The correct FQBN is: `arduino:avr:nano:cpu=atmega328old`

**Comment by klao** [comment]
> for the old bootloader, the fqbn is "arduino:avr:nano:cpu=atmega328pld".

In case someone finds this (like I did). It's a typo, the correct fqbn is `arduino:avr:nano:cpu=atmega328old`.
