### ISSUE TITLE
Set Baud Rate for port

### ISSUE THREAD

**Issue by davidgs** [arduino/arduino-cli#305]
### Current behavior
Baud rate for sketch upload is determined by the board file. This is fine for most boards, but some require adjusting the baud rate. 

### Expected behavior

Would be really nice to be able to override the default baud rate with a`-b 115200`. The Wemos D1 (ESP8266) sometimes works at the default baud rate, but more often than not it requires a slower baud rate (115200 seems reliable). 

### Environment

- CLI version (output of `arduino-cli version`):
arduino-cli Version: 0.3.7-alpha.preview 
- Go version (if building from sources):
go version go1.12.7 darwin/amd64
- OS version:
Mac OS X 10.14.5

**Comment by per1234** [comment]
You set the upload baud rate for ESP8266 boards via the `baud` property in the FQBN (fully qualified board name). For example, if you wanted to upload a sketch named Foo at 115200 to the WeMos D1 Mini, the command would look like this:
```
arduino-cli upload --fqbn esp8266:esp8266:d1_mini:xtal=80,vt=flash,exception=disabled,ssl=all,eesz=4M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200 Foo
```
