### ISSUE TITLE
upload -t(--verify) enables "Verbose" instead of "Verify"

### ISSUE THREAD

**Issue by cjsieh** [arduino/arduino-cli#31]
$ go/bin/arduino-cli-0.2.1-alpha.preview-linux64 upload -t --port /dev/ttyUSB0  -b arduino:avr:nano:cpu=atmega328 Blink 

avrdude: Version 6.3, compiled on Jan 17 2017 at 11:00:16

<snipped>

avrdude: 928 bytes of flash 
-------------------------------------------------
Above shows --verbose and NO --verify
-----------------------------------------------------------------------------------------------------------
$ ./arduino-cli upload -t -v --port /dev/ttyUSB0  -b arduino:avr:nano:cpu=atmega328 ~/Blink
avrdude: Version 6.3, compiled on Jan 17 2017 at 11:00:16
  
<snipped> 

avrdude: 928 bytes of flash written
avrdude: verifying flash memory against /home/siehputz/Blink/Blink.arduino.avr.nano.cpu=atmega328.hex:
avrdude: load data flash data from input file /home/siehputz/Blink/Blink.arduino.avr.nano.cpu=atmega328.hex:
avrdude: input file /home/siehputz/Blink/Blink.arduino.avr.nano.cpu=atmega328.hex contains 928 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.13s

avrdude: verifying ...
avrdude: 928 bytes of flash verified

-------------------------------------------------------------------------------------------------------
This upload.go was patched with
-------------------------------------------------------------------------------------------------------
--- ../../../../Downloads/upload.go	2018-09-04 10:49:25.040860707 -0500
+++ arduino-cli/commands/upload/upload.go	2018-09-02 18:39:56.060296516 -0500
@@ -49,7 +49,7 @@
 		"Fully Qualified Board Name, e.g.: arduino:avr:uno")
 	uploadCommand.Flags().StringVarP(&flags.port, "port", "p", "",
 		"Upload port, e.g.: COM10 or /dev/ttyACM0")
-	uploadCommand.Flags().BoolVarP(&flags.verbose, "verify", "t", false,
+	uploadCommand.Flags().BoolVarP(&flags.verify, "verify", "t", false,
 		"Verify uploaded binary after the upload.")
 	uploadCommand.Flags().BoolVarP(&flags.verbose, "verbose", "v", false,
 		"Optional, turns on verbose mode.")

-----------------------------------------------------------------------------------------------------

**Comment by cjsieh** [comment]
The example of it broken did not seem to show up.  Here it is again.

$ go/bin/arduino-cli-0.2.1-alpha.preview-linux64 upload -t --port /dev/ttyUSB0  -b arduino:avr:nano:cpu=atmega328 Blink 

avrdude: Version 6.3, compiled on Jan 17 2017 at 11:00:16

.. snipped
        
avrdude: writing flash (928 bytes):

Writing | ################################################## | 100% 0.16s

avrdude: 928 bytes of flash written

**Comment by cmaglie** [comment]
Thank you!
