### ISSUE TITLE
install.sh fails on installing arduino-cli to windows 10

### ISSUE THREAD

**Issue by noweare1** [arduino/arduino-cli#334]
### Current behavior

The script identified my system as
"
MINGW 32BIT WINDOWS
OS=MINGW32_NT-10.0-WOW
"
the script returned httpStatusCode = 404

intermediate output from install.sh
"
Did not find a release for your system: Windows 32bit
Trying to find a release using the GitHub API.
LATEST_RELEASE_URL=https://api.github.com/repos/arduino
"
final error msg from install.sh
"
Sorry, we dont have a dist for your system: Windows 32bit
You can request one here: https://github.com/Arduino/arduino-cli/issues
Failed to install arduino-cli
"

### Expected behavior
A successfull install

### Environment
windows 10  64bit

**Comment by masci** [comment]
@noweare1 I've a patch up for review that should fix the problem. In the meantime, you can test it out by running 
```
curl https://raw.githubusercontent.com/arduino/arduino-cli/massi/install-mingw/install.sh | sh
```

Thanks for reporting!
