### ISSUE TITLE
[config] `config dump --format json` provides an invalid JSON format

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#342]
### Current behavior

```
arduino-cli config dump --format json
```

Provides an invalid JSON format.

```json
proxy_type: auto
sketchbook_path: /Users/akos.kitta/Documents/Arduino
arduino_data: /Users/akos.kitta/Library/Arduino15
board_manager: {}
```

### Expected behavior

I want to parse the result with JS, so I would expect a result that can be processed with:

```js
JSON.parse(myOutput);
```

### Environment

- CLI version (output of `arduino-cli version`):
`arduino-cli Version: nightly-83 Commit: bd20ce6`
- OS and platform:
`macOS 10.14.6 (18G87)`

**Comment by masci** [comment]
This is fixed on master
