### ISSUE TITLE
Add network-discovery support

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-cli#344]
Network discovery tool: https://github.com/arduino/mdns-discovery

This should allow OTA and is required to implement #69

**Comment by thekunalsaini** [comment]
Hi to all,
I m Kunal Saini . I like to work with you in this project.
What I have planned is given below :

# Implementation
We can attach any WiFi module or bluetooth module or mount ethernet on arduino and then write a functionality through which it can appear in network.

Functionality helps to make available device in network.
Power is given through Battery or any other source.
This is my idea how we can do it.

Thank you

**Comment by thekunalsaini** [comment]
@cmaglie Any suggestion regarding implementation most welcome

**Comment by rtek1000** [comment]
Hello guys, I don't want to be too boring, but it will be difficult for people to test this IDE 2.0 if they don't have the network port.

Do you have any expectations of being able to add this functionality?

Do you have any priority of adding this network port?

Thank you.

**Comment by kmorris1077** [comment]
Not having the network port capability is a total deal breaker for many of us with esp32s in field installations who want to use the 2.0 IDE.

**Comment by ubidefeo** [comment]
@kmorris1077 
we are in the peocess of closing our RFC for pluggable discovery.
At that point it would be up to platform implementers to write their discovery layer

**Comment by StarMiner99** [comment]
im also not using the arduino 2 ide because i cant programm my esp-01s without cables and an ftdi adapter its to much work to connect it every time.
