### ISSUE TITLE
Make keyword argument of arduino-cli core search optional

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-cli#354]
### Current behavior

`arduino-cli lib search` lists all libraries in the index. However, `arduino-cli core search` does not mirror this behavior:
```
Error: requires at least 1 arg(s), only received 0
Usage:
  arduino-cli core search <keywords...> [flags]
```

### Expected behavior
`arduino-cli core search` should be consistent with the `arduino-cli lib search` interface

### Environment

- CLI version: built from source at https://github.com/arduino/arduino-cli/commit/4d36bac05eaf5ba91eba1e23d34c93f600eea9c4
- OS and platform: Windows 10 64 bit

**Comment by HowJMay** [comment]
I am the newcomer of this project.
May I take this issue?

**Comment by masci** [comment]
@HowJMay sure thing, go for it!
