### ISSUE TITLE
Null pointer if target .ino is a folder

### ISSUE THREAD

**Issue by facchinm** [arduino/arduino-cli#358]
### Current behavior
`./arduino-cli --debug compile -b anything:something:meh ~/Arduino/Blink` crashes with null pointer dereference if `~/Arduino/Blink` contains a **folder** called `Blink.ino`

### Expected behavior

Malformed ino files should be recognized and skipped.

### Environment

- CLI version (output of `arduino-cli version`): nightly-4-gcb3c79b 
- OS and platform: linux x86_64

**Comment by shade34321** [comment]
Has this already been worked on? If not I'd like to try it.

**Comment by masci** [comment]
@shade34321 all yours!

**Comment by shade34321** [comment]
Sweet, Thanks!

**Comment by masci** [comment]
@shade34321 FYI it seems #42 indirectly fixes this issue

**Comment by d-a-v** [comment]
#42 or #421 ?

**Comment by masci** [comment]
@d-a-v 421, autocompletion tricked me :)

**Comment by shade34321** [comment]
Oh ok. Guess I won't need to work on this. I'll see if I can find something else easy to work on. Thanks!
