### ISSUE TITLE
Libraries installation/uninstallation name inconcistency

### ISSUE THREAD

**Issue by Renaud11232** [arduino/arduino-cli#362]
## Bug Report

The name to use when installing or uninstalling libraries is inconsistent

### Current behavior

Installing libraries work as intented. ie:

```
PS C:\Users\gaspa\Downloads> .\arduino-cli.exe lib install "LiquidCrystal I2C"
Downloading LiquidCrystal I2C@1.1.2...
LiquidCrystal I2C@1.1.2 already downloaded
Installing LiquidCrystal I2C@1.1.2...
Installed LiquidCrystal I2C@1.1.2
```
But trying to remove the library using the name used when installing, does not always remove the library.
```
PS C:\Users\gaspa\Downloads> .\arduino-cli.exe lib uninstall "LiquidCrystal I2C"
Library LiquidCrystal I2C is not installed
```
In this case I had to replace the space with a `_`
```
PS C:\Users\gaspa\Downloads> .\arduino-cli.exe lib uninstall "LiquidCrystal_I2C"
Uninstalling LiquidCrystal_I2C@1.1.2...
```

### Expected behavior

The libraries should be installed and uninstalled using the same name

#### CLI version
```
PS C:\Users\gaspa\Downloads> .\arduino-cli.exe version
arduino-cli.exe Version: 0.4.0 Commit: =98b7be9
```
#### OS/Platform

Windows 10 Pro build 1903

**Comment by HowJMay** [comment]
If possible, could I try this one?

**Comment by masci** [comment]
@HowJMay all yours! :smile: 
Thanks!

**Comment by HowJMay** [comment]
My pleasure

**Comment by HowJMay** [comment]
@masci May I ask that whether all the library with the following link can be downloaded with arduino-cli ?
https://www.arduinolibraries.info/

**Comment by masci** [comment]
@HowJMay http://downloads.arduino.cc/libraries/library_index.json contains all the libraries that can be installed out of the box with the CLI, then users can add any number of additional json indexes listing their own "unofficial" libraries.

**Comment by HowJMay** [comment]
Thanks

**Comment by cmaglie** [comment]
> May I ask that whether all the library with the following link can be downloaded with arduino-cli ?
https://www.arduinolibraries.info/

AFAIK this website takes the list from our library_index.json so: yes.

**Comment by HowJMay** [comment]
Thank you !
