### ISSUE TITLE
Cannot compile for Mega 2560 R3

### ISSUE THREAD

**Issue by NormanDunbar** [arduino/arduino-cli#38]
Linux 64bit.
Linux Mint 18.3.
Dell Vostro 1720.

Of my three boards, only the Mega is recognised:

````
$ arduino-cli board list
FQBN            	Port        	ID       	Board Name                       
arduino:avr:mega	/dev/ttyACM0	2341:0042	Arduino/Genuino Mega or Mega 2560
````

I have the avr core installed:

````
$ arduino-cli core list
ID         	Installed	Latest	Name              
arduino:avr	1.6.21   	1.6.21	Arduino AVR Boards
````

However, compilations fail:

````
$ arduino-cli compile  --fqbn arduino:avr:mega Arduino/MyFisrtSketch -v

Using board 'mega' from platform in folder: /home/norman/.arduino15/packages/arduino/hardware/avr/1.6.21
Using core 'arduino' from platform in folder: /home/norman/.arduino15/packages/arduino/hardware/avr/1.6.21
Detecting libraries used...
/home/norman/.arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -w -x c++ -E -CC -mmcu= -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/home/norman/.arduino15/packages/arduino/hardware/avr/1.6.21/cores/arduino -I/home/norman/.arduino15/packages/arduino/hardware/avr/1.6.21/variants/mega /tmp/arduino-sketch-EA97366D8DD5BAD4DFBCF42C5DC29A82/sketch/MyFisrtSketch.ino.cpp -o /dev/null
avr-g++: error: missing device or architecture after '-mmcu='
Error: exit status 1
Compilation failed.
````

Cheers,
Norm.

**Comment by tab4moji** [comment]
try fqbn `arduino:avr:mega:cpu=atmega2560`.

the others:

- `arduino:avr:uno`
- `arduino:avr:pro:cpu=8MHzatmega168`
- `arduino:avr:pro:cpu=16MHzatmega168`
- `arduino:avr:pro:cpu=8MHzatmega328`
- `arduino:avr:pro:cpu=16MHzatmega328`
- `arduino:avr:nano:cpu=atmega168`
- `arduino:avr:nano:cpu=atmega328`
- `arduino:avr:nano:cpu=atmega328old`
- `arduino:avr:atmegang:cpu=atmega168`
- `arduino:avr:atmegang:cpu=atmega8`
- `arduino:avr:leonardo`
- `arduino:avr:mega:cpu=atmega2560`
- `arduino:avr:mega:cpu=atmega1280`

**Comment by NormanDunbar** [comment]
Thanka @tab4moji - I'll give that a try. Is it documented? I hope not as I couldn't find it! ;-)

Cheers,
Norm.

**Comment by tab4moji** [comment]
sorry, i dont know document.
i wonder if document is ...
--board
https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc#options

**Comment by NormanDunbar** [comment]
Good Morning @tab4moji - your cpu=atmega2560 worked perfectly and my code compiled. Thank you.

I have read the docs you pointed me too as well, very helpful.

Cheers,
Norm.

**Comment by ru2saig** [comment]
I faced a similar issue with arduino-cli version 0.29.0-arch, on Arch Linux. I installed it from the package repos. 

To fix the issue, I follow this https://www.shellhacks.com/arduino-dev-ttyacm0-permission-denied/ blog post. 

For me, the group was uucp. Running the `sudo usermod -a -G uucp <username>` and logging out and logging in fixed the issue.
