### ISSUE TITLE
Include library from local folder

### ISSUE THREAD

**Issue by tage64** [arduino/arduino-cli#397]
Hello,
How do I install a library from a local folder. I've downloaded grbl and tried to include it as a library, but it seems I cannot install local libraries.

Is this possible? Or have I miss understood something?

Best regards,
Tage

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.

**Comment by matthijskooijman** [comment]
See https://www.arduino.cc/en/Guide/Libraries for guidance on where and how libraries should be installed.
