### ISSUE TITLE
Does not create sketchbook_home if not present. Sketch new then fails.

### ISSUE THREAD

**Issue by NormanDunbar** [arduino/arduino-cli#40]
When creating a new sketch with `arduino-cli sketch new myFirstSketch`, if the directory `/home/my_name/Arduino` (on Linux) is not present, the creation fails when attempting to `mkdir` the sketch directory. It should use the `mkdir -p` command instead.

Linux Mint 64 bit.
Arduino-cli 0.2.1-alpha-preview.

Loving this tool by the way. Great work.

Cheers,
Norm.

**Comment by cmaglie** [comment]
This feature will be added on the next alpha release.

**Comment by NormanDunbar** [comment]
Nice one @cmaglie , thanks.
