### ISSUE TITLE
upload flag to compile command doesn't work without output name

### ISSUE THREAD

**Issue by ademuri** [arduino/arduino-cli#409]
Specifying the `-u` flag to `compile` doesn't work unless I also specify `-o` to give an output file name. For example,

this doesn't work:
```text
$ arduino-cli compile -b "arduino:samd:mkrzero" -p /dev/ttyACM1 -u serial_test.ino
Sketch uses 11288 bytes (4%) of program storage space. Maximum is 262144 bytes.
Error during Upload: cannot open sketch: stat serial_test.ino/serial_test.ino.arduino.samd.mkrzero.bin: not a directory
```

but this does:
```text
$ arduino-cli compile -b "arduino:samd:mkrzero" -p /dev/ttyACM1 -u serial_test.ino -o serial_test.bin
```

It'd be nice if this flag worked without `-o`, so that the output file would automatically be generated in the temp dir.

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-cli/pull/690
