### ISSUE TITLE
Custom board is detected as "Unknown"

### ISSUE THREAD

**Issue by intrigus** [arduino/arduino-cli#456]
### Current behavior

````bash
./arduino-cli board list
Port         Type              Board Name FQBN Core
/dev/ttyACM0 Serial Port (USB) Unknown
````

The connected board is not recognized.

### Expected behavior

````bash
./arduino-cli board list
Port         Type              Board Name FQBN Core
/dev/ttyACM0 Serial Port (USB) ftduino:avr:ftduino
````
I'd expect the device to get recognized. 
The arduino IDE correctly recognizes it.
The pid and vid are defined in the extension here:
https://github.com/harbaum/ftduino/blob/master/ftduino/boards.txt#L3-L7
Is there something else that needs to be done to recognize a custom board?
### Environment

- CLI version (output of `arduino-cli version`): arduino-cli Version: 0.6.0 Commit: 3a08b07
- OS and platform: Linux.

**Comment by cmaglie** [comment]
It may be that the vid/pid pairs start with the progressive number `1` instead of `0`:

```
ftduino.name=ftDuino
ftduino.vid.1=0x1c40   <--- should be vid.0
ftduino.pid.1=0x0537
ftduino.vid.2=0x1c40
ftduino.pid.2=0x0538
```

May you try to change the above lines with:

```
ftduino.name=ftDuino
ftduino.vid.0=0x1c40
ftduino.pid.0=0x0537
ftduino.vid.1=0x1c40
ftduino.pid.1=0x0538
```

and see if this fixes the problem?
