### ISSUE TITLE
[proposal][feature-request] Make the daemon port configurable

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#485]
### Current behavior

Currently, the port for the CLI daemon is always:
https://github.com/arduino/arduino-cli/blob/ef6463bf36bce1cdd97c7a1bb26932d77051ce02/cli/daemon/daemon.go#L37

According to [this comment](https://github.com/arduino/arduino-pro-ide/issues/134#issuecomment-553537737), the hard-coded port is excluded on Windows when Hyper-V is installed, so clients cannot connect to the running daemon.

```
failed to listen: listen tcp :50051: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

Would it be possible to give the desired daemon port as an argument to the CLI? We could let the OS pick a random, available port for us, and we could connect to it. Thoughts?

### Environment

- CLI version (output of `arduino-cli version`):
- OS and platform:

**Comment by masci** [comment]
Waiting for #487 to be merged before implementing this
