### ISSUE TITLE
[Question] Arduino-Cli and Network

### ISSUE THREAD

**Issue by GiannisRallis** [arduino/arduino-cli#486]
Hello i want to work with arduino-cli and network shiled is there any way to do this? I am asking because i am reading only for usb connection. Does anyone knows about network communication whit this CLI? 

Thank you !

**Comment by masci** [comment]
Hi @GiannisRallis the CLI is currently missing network discovery capabilities, see https://github.com/arduino/arduino-cli/issues/344 - so yeah, the only way to talk with a board at the moment is using the serial port. 

Does this answer your question?
