### ISSUE TITLE
HowTo Compile Multi.ino to custom named hex-file?

### ISSUE THREAD

**Issue by harryberlin** [arduino/arduino-cli#496]
Is it possible to compile multi.ino sketch to custom named/output-path hex-file?
Further nice option would be to set some defines from command line (i.e. debug)

**Comment by per1234** [comment]
>Is it possible to compile multi.ino sketch to custom named/output-path hex-file?

Sure, just use the `--output` option of `arduino-cli compile`. For example:
```
arduino-cli compile --output Bar/asdf multi
```
will output asdf.hex to the Bar folder.

>Further nice option would be to set some defines from command line (i.e. debug)

See: https://github.com/arduino/arduino-cli/issues/210
