### ISSUE TITLE
32-Bit Apps will no longer work on macOS Catalina

### ISSUE THREAD

**Issue by Topppy** [arduino/arduino-cli#520]
## Bug Report

compile command  not work 
### Environment

- CLI version (output of `arduino-cli version`): 0.5.0
- OS and platform:
macOS Catalina

### Additional context

some lib is still 32bit

**Comment by a7hybnj2** [comment]
This affects me too.

```
arduino-cli compile --fqbn arduino:avr:uno ./
Build options changed, rebuilding all
Error: fork/exec /Users//Library/arduino15/packages/builtin/tools/ctags/5.8-arduino11/ctags: bad CPU type in executable
Compilation failed.
make: *** [all] Error 1
```

**Comment by rsora** [comment]
Hi @Topppy, thanks for your bug report! 
The tool you mentioned was rebuilt and updated in the CLI list of additional tools to download in this PR: https://github.com/arduino/arduino-cli/issues/520

Could you please update your CLI version to the latest (0.7.2) and try again?

**Comment by Topppy** [comment]
> Hi @Topppy, thanks for your bug report!
> The tool you mentioned was rebuilt and updated in the CLI list of additional tools to download in this PR: #520
> 
> Could you please update your CLI version to the latest (0.7.2) and try again?

Thanks for your work.
