### ISSUE TITLE
How about add options for mirror sites?

### ISSUE THREAD

**Issue by quchunguang** [arduino/arduino-cli#56]
`arduino-cli core install arduino:avr` download the core with only about 30MB, i have take more than one hour! How about add options in `arduino` to target witch mirror to use, like Debian or pip do? I can make two fast mirror for universities and public in China.

**Comment by gvarisco** [comment]
Since this ticket got opened, we have added a global CDN with PoPs all around the globe. @quchunguang could you please let us know if you encounter any further speed issue downloading core(s) or other files from our endpoint?

Feel free to re-open this ticket if the speed issue still occurs.
