### ISSUE TITLE
Which core for Arduino UNO R3?

### ISSUE THREAD

**Issue by quchunguang** [arduino/arduino-cli#57]

**Comment by quchunguang** [comment]
I found that `arduino-cli compile --fqbn arduino:avr:uno Arduino/MyFirstSketch` works, mostly by guess.
But the FQBN and Board Name always be none and unknown by `arduino-cli board list`.

**Comment by per1234** [comment]
Is is a clone of an Uno? If so, this is likely a duplicate of https://github.com/arduino/arduino-cli/issues/37.

**Comment by NormanDunbar** [comment]
Try `arduino-cli` board listall` 

Cheers,
Norm.

**Comment by quchunguang** [comment]
> ? If so, this is

Yes. the same output with `lsusb`
```
Bus 007 Device 003: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
```
