### ISSUE TITLE
Install script doesn't work properly on v0.8.0

### ISSUE THREAD

**Issue by SConaway** [arduino/arduino-cli#584]
## Bug Report
Install script doesn't work properly on v0.8.0. I think this might be because the binary is not chmod-ed +x.

````
macos-mojave-10:~ steven$ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
Installing in /Users/steven/bin
ARCH=64bit
OS=macOS
Using curl as download tool
TAG=0.8.0
CLI_DIST=arduino-cli_0.8.0_macOS_64bit.tar.gz
Downloading https://downloads.arduino.cc/arduino-cli/arduino-cli_0.8.0_macOS_64bit.tar.gz
arduino-cli not found. You might want to add /Users/steven/bin to your $PATH
sh: line 185: /Users/steven/bin/arduino-cli: Permission denied
Failed to install arduino-cli
macos-mojave-10:~ steven$ 
````

### Environment

- CLI version (output of `arduino-cli version`): N/A
- OS and platform: macOS 10.14.4 and 10.13.6

**Comment by zmoog** [comment]
Hi @SConaway, thank you for taking some time to write this bug report!

The install script is failing due to a missing execution flag on the binary: we are investigating to find the root cause, but in meantime we'll fix the v0.8.0 files in our CDN.

**Comment by zmoog** [comment]
@SConaway can you delete the old binary from your machine and try to run the install script again?

**Comment by SConaway** [comment]
That fixed it. 

[Failing build](https://travis-ci.com/SConaway/travis-arduino/jobs/287666514)
[Working build](https://travis-ci.com/SConaway/travis-arduino/jobs/288158674)

**Comment by zmoog** [comment]
Great! Thank you for your feedback, happy hacking!
