### ISSUE TITLE
[proposal] Please provide us a JSON schema for the new arduino-cli.yaml config file

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-cli#587]
### Current behavior

The new `arduino-cli.yaml` config file, the new `Settings` API everything works perfectly 💪, however, I am missing the JSON schema for the configuration file. As a consumer of the CLI, I want to programmatically validate the config file before I use it.

As a start, the actual JSON schema could be released with the CLI, inside the archive. Once it gets rock solid, perhaps it could be published to http://schemastore.org/json/.

### Environment

- CLI version (output of `arduino-cli version`):
- OS and platform:

**Comment by umbynos** [comment]
AC: Structural validation of the file should be sufficient. The process should be as automated as possible.
