### ISSUE TITLE
"board list" command doesn't follow proxy configuration

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-cli#660]
The command `arduino-cli board list` should use proxy to call board VIP/PID identification API, but this is not implemented yet: https://github.com/arduino/arduino-cli/blob/6903076cd3e0ba05791dbd248907a7d42c7f9e16/commands/board/list.go#L57

We may consider to use `downloader` for this piece too.

**Comment by cmaglie** [comment]
fixed by #672

**Comment by j-d-salinger** [comment]
It is 2023, and it doesn't follow the http_proxy and https_proxy global linux variables

**Comment by cmaglie** [comment]
The proxy setting must be written in the configuration file using the `network.proxy` key.

If you want to request support for `http_proxy` and `https_proxy` env vars, please open a new issue and provide a link to the env var specification.
