### ISSUE TITLE
how to get output without *.elf and *.with_bootloader.hex

### ISSUE THREAD

**Issue by harryberlin** [arduino/arduino-cli#671]
### Current behavior

arduino-cli compile -b arduino:avr:mega -o C:\temp\MEGA.hex C:\Users\Christian\Downloads\arduino-cli\Sketch

How to get output file to output path, but without *.elf and *.with_bootloader.hex files.
That means, i'd to get only the .hex file.

### Expected behavior

No

### Environment

- CLI version (output of `arduino-cli version`): 0.10
- OS and platform: Windows, Linux

### Additional context

No

**Comment by umbynos** [comment]
Hi @harryberlin, currently the latest version of the cli (0.27.1) has a flag called `--output-dir` which **Save build artifacts in this directory**. For example:
`arduino-cli compile -b arduino:megaavr:uno2018 ~/Blink -v --output-dir /tmp/cose/`:
```
ll /tmp/cose/
total 108K
-rwxrwxr-x 1 umberto umberto 1,5K ott 13 12:42 Blink.ino.bin*
-rw-rw-r-- 1 umberto umberto   34 ott 13 12:42 Blink.ino.eep
-rwxrwxr-x 1 umberto umberto  44K ott 13 12:42 Blink.ino.elf*
-rw-rw-r-- 1 umberto umberto 4,3K ott 13 12:42 Blink.ino.hex
-rw-rw-r-- 1 umberto umberto  36K ott 13 12:42 Blink.ino.map
-rw-r--r-- 1 umberto umberto 2,0K ott 13 12:42 Blink.ino.with_bootloader.bin
-rw-rw-r-- 1 umberto umberto 4,9K ott 13 12:42 Blink.ino.with_bootloader.hex
```
We do not offer the possibility to export only some of the build artifacts.
