### ISSUE TITLE
Place build related files in a .build sub-directory

### ISSUE THREAD

**Issue by woolseyj** [arduino/arduino-cli#673]
### Current Behavior
The various build related files, e.g. *.elf, *.hex, and sketch.json, can clutter up a sketch workspace directory.

### Requested Behavior
I suggest these types of files be placed in a hidden **.build** sub-directory that can be more easily ignored by users and tools such as Git.

**Comment by cmaglie** [comment]
This has been fixed in #687.
Eventually we decided to place the builds inside the `build` folder (without the `.` dot).

**Comment by woolseyj** [comment]
Thank you.
