### ISSUE TITLE
arduino-cli_latest_Linux_64bit.tar.gz contains version 0.9.0 instead of latest 0.10.0

### ISSUE THREAD

**Issue by phd** [arduino/arduino-cli#677]
https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz [1]
and other latest packages contain version 0.9.0 instead of latest 0.10.0 release.

[1] https://arduino.github.io/arduino-cli/installation/#download-the-latest-packages

**Comment by rsora** [comment]
Hi @phd,
Thanks for the heads up! Can you please try again?

**Comment by phd** [comment]
All links work fine now. Thanks!
