### ISSUE TITLE
Does OTA work in arduino-cli?

### ISSUE THREAD

**Issue by brusherru** [arduino/arduino-cli#69]
I see `networkBoards` list when I call `arduino-cli board list --format json`, but it's always empty, even when I see the board in the Arduino IDE.

I tested it with `esp8266:esp8266:wifi_slot` board on MacOS Sierra.

I see that you are using `monitor.Network()` in the `board/list.go`, so I assume it should work. But it's not.

Is this a real bug or it just not implemented yet?

**Comment by unixbigot** [comment]
Here's a makefile snippet that provides a temporary workaround for doing OTA with the CLI:

'make find' to list network boards, 'make ota' to upload.   Make ota takes board hostname.  If you want to skip the zeroconf query and use the ip, do "make ota IP=1.2.3.4"

```
ota: $(OBJ)
	@if [ -z "$$IP" ] ; then \
		IP=`avahi-browse -ptr  "_arduino._tcp" | egrep ^= | cut -d\; -f4,8,9 | grep ^$$DEVICE | cut -d\; -f2` -p `avahi-browse -ptr  "_arduino._tcp" | egrep ^= | cut -d\; -f4,8,9 | grep ^$$DEVICE | cut -d\; -f3` ;\
	fi ;\
	python $(OTAPROG) -i $(IP) "--auth=$(OTAPASS)" -f $(OBJ)

find:
	@if [ `uname -s` = Darwin ] ; then \
		dns-sd -B _arduino._tcp ;\
	else \
		avahi-browse -ptr  "_arduino._tcp" | egrep ^= | cut -d\; -f4,8,9 ;\
	fi
```

**Comment by thekunalsaini** [comment]
@brusherru  yes it can work

**Comment by rsora** [comment]
@brusherru @thekunalsaini 
Roberto from Arduino Team here: 
Currently OTA support is not included in the CLI. 
Our plan is to implement a "Pluggable discovery" feature in the near future that will allow to support OTA.
Workaround are possible as @unixbigot reported, but there is no CLI native support ATM.
Cheers!
