### ISSUE TITLE
Passing additional configuration  to arduino-cli compile

### ISSUE THREAD

**Issue by panigrah** [arduino/arduino-cli#698]
Arduino-ide allows setting up of additional build parameters specific to each board. e.g. when building for an esp32 board i can set configuration parameters such as partition in the arduino IDE. 

How do I configure a partition when using arduino-cli? It always picks the default.

**Comment by per1234** [comment]
You do this by specifying the board configuration options in the arduino-cli command's `--fqbn` option.

For example, if you wanted to compile with the equivalent of having the **Tools > Partition Scheme > Minimal (1.3MB APP/700KB SPIFFS)** setting selected in the Arduino IDE, you would use this command:
```
arduino-cli compile --fqbn esp32:esp32:esp32:PartitionScheme=minimal
```
As you discovered, when you don't specify a configuration option value in the FQBN (e.g., `esp32:esp32:esp32`), the default option is used.

I have provided more information on how custom boards options work with FQBNs and how to determine the correct FQBN in these earlier issues:
- https://github.com/arduino/arduino-cli/issues/591#issuecomment-589644040
- https://github.com/arduino/arduino-cli/issues/138#issuecomment-459169051

We probably do need to further improve the documentation to make this easier for the Arduino CLI users, but we have an existing issue about that (https://github.com/arduino/arduino-cli/issues/355), so I'll go ahead and close this one.
