### ISSUE TITLE
AVR baud rate error with Arduino Mega

### ISSUE THREAD

**Issue by notkevinjohn** [arduino/arduino-cli#70]
I am trying to use the CLI to upload code to an Arduino Mega. It complains that:
`avrdude: invalid baud rate specified '{upload.speed}'`

I am wondering if maybe the FQBN I am getting (arduino:avr:mega) might still have some kind of place holder text when trying to resolve the appropriate baud rate? How can I investigate what the baud rate being specified for this FQBN is?

Here is the command I am executing:
`arduino upload -p /dev/ttyACM0 --fqbn arduino:avr:mega  ~/Arduino/HelloWorld/`

The board seems to be successfully recognized when searched for:
```
arduino board list
FQBN                    Port            ID              Board Name
arduino:avr:mega        /dev/ttyACM0    2341:0042       Arduino/Genuino Mega or Mega 2560
```

**Comment by borisgk** [comment]
Works fine with a fqbn of 

`--fqbn arduino:avr:mega:cpu=atmega2560`

[Here](https://qiita.com/tab4moji/items/1c760fc2ca48c9ee10ee) is some discussion, but I can't read it.

**Comment by notkevinjohn** [comment]
That solved the problem, thanks.
