### ISSUE TITLE
Put a library inside a sketch folder

### ISSUE THREAD

**Issue by grafalex82** [arduino/arduino-cli#71]
My sketch depends on a slightly modified library. I do not want to install this library to the system as other projects may not be good with such changes.

What is the way to put library inside the sketch folder? I tried different options found on the Internet:
- sketchdir\Libs\Mylib\Mylib.cpp
- sketchdir\libraries\Mylib\Mylib.cpp
- sketchdir\libraries\Mylib\src\Mylib.cpp
- sketchdir\src\libraries\Mylib\src\Mylib.cpp
.. and various mixes of approaches above.

How does arduino-cli process local libraries?

**Comment by per1234** [comment]
arduino-cli does recursive compilation of the contents of the `src` subfolder of the sketch. So you can bundle libraries under that folder:
```
Sketch
|_Sketch.ino
|_src
   |_MyLib
      |_src
         |_MyLib.h
```
Then the `#include` directive in Sketch.ino would look like this:
```c++
#include "src/MyLib/src/MyLib.h"
```

As for support for the standard Arduino library installation style in a subfolder of the sketch, we have a previous request: https://github.com/arduino/arduino-cli/issues/32
