### ISSUE TITLE
Core search command fails with uppercase framework

### ISSUE THREAD

**Issue by jmchiappa** [arduino/arduino-cli#710]
### Current behavior
executing `arduino-cli.exe core search STM32` fails even if framework is already installed.

The search always fails due to the search code which put in lowercase :
https://github.com/arduino/arduino-cli/blob/ebc28e1bb15818b24b180221a898a50c8be306c7/cli/core/search.go#L58

### Expected behavior
Searching (e.g. 'STM32' for STM32duino) framework should return the expected framework with all supported version

### Environment

- CLI version : arduino-cli.exe Version: 0.10.0 Commit: ec5c3ed
- OS and platform:
windows 10 x64 build 18363

**--- EDIT ---**
Even after rebuilding a new version without the `strings.ToLower` it doesn't seem to work as expected.
Not sure about the behavior of this command...

**Comment by umbynos** [comment]
This should be solved here https://github.com/arduino/arduino-cli/pull/1904, please try it out
