### ISSUE TITLE
"None" item shown in documentation index when viewing docs versions previous to the addition of a new page

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-cli#724]
### Current behavior
Open the user documentation for the 0.10 release:
https://arduino.github.io/arduino-cli/0.10/

The index has a "None" item where the "Sketch specification" page will be:
![Clipboard01](https://user-images.githubusercontent.com/8572152/82979329-a0846580-9f9b-11ea-8154-f118a85a4d38.png)

### Expected behavior
No index item should be shown for pages created after the selected version.

### Environment

- CLI version (output of `arduino-cli version`): N/A
- OS and platform: Ubuntu and Windows with Firefox and Chrome

**Comment by umbynos** [comment]
![image](https://user-images.githubusercontent.com/34278123/85988022-bfd53f00-b9ee-11ea-999e-ef5d69d29cb0.png)
Fixed in 0.11
