### ISSUE TITLE
Can't use standard STL includes in library code

### ISSUE THREAD

**Issue by grafalex82** [arduino/arduino-cli#86]
When trying to compile DMStepper library arduino-cli hit #include <vector> (see [https://github.com/toxnico/DMStepper/blob/master/src/dmsteppergroup.h](https://github.com/toxnico/DMStepper/blob/master/src/dmsteppergroup.h)) and tried to interpret this as an another library dependency

```
Alternatives for vector: []
ResolveLibrary(vector)
  -> candidates: []
In file included from /home/pi/Arduino/libraries/DMStepper/src/dmsteppergroup.cpp:1:0:
/home/pi/Arduino/libraries/DMStepper/src/dmsteppergroup.h:4:18: fatal error: vector: No such file or directory
 #include <vector>
                  ^
compilation terminated.

```

I have no idea why it did not find the include file - toolset has it at .packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/arm-none-eabi/include/c++/4.8.3

**Comment by GeraldR63** [comment]
Hello Grafalex,

to be able to compile dmstepper it's required to add line below to your sketch:

// ArduiniSTL required in front of dmstepper.h.  Probably you have to install this 
#include <ArduinoSTL.h>
#include <dmstepper.h>

Than you can compile and upload.

regards
Gerald

**Comment by grafalex82** [comment]
Thanks. I'll try this

**Comment by facchinm** [comment]
Closing as fixed
