### ISSUE TITLE
update-index : panic: runtime error:

### ISSUE THREAD

**Issue by wjwieland** [arduino/arduino-cli#87]
**Version:**    arduino-cli version 0.3.2-alpha.preview
**Plafform:**  RPi3/RPi2B+

**Note:  This issue is intended to address only the RPi (arm) version.  The 64bit version runs fine on Ubuntu 18.04**

**_Results of update-index_**
```
 arduino-cli lib update-index
 0 / ? [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------=]   0.00%panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x123d4]

goroutine 18 [running]:
sync/atomic.addUint64(0x1336bed4, 0x1000, 0x0, 0x1000, 0x1000)
        /home/jenkins/go1.10.2-patched/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).AsyncRun(0x1336bec0)
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:82 +0x17c
created by github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).RunAndPoll
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:61 +0x70
```

```
wjw@weatherrack3:~ $ **arduino-cli core update-index**
 0 / 233181 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x123d4]

goroutine 18 [running]:
sync/atomic.addUint64(0x12977184, 0xe78, 0x0, 0x1000, 0xe78)
        /home/jenkins/go1.10.2-patched/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).AsyncRun(0x12977170)
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:82 +0x17c
created by github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).RunAndPoll
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:61 +0x70

```

**Comment by cmaglie** [comment]
Are you running the cli without any custom config file?

**Comment by wjwieland** [comment]
@cmaglie 
I have the standard .cli-config.hml in ~/$HOME if that is what you mean.  
**The contents of which are:**
```
proxy_type: auto
sketchbook_path: /home/wjw/Arduino
arduino_data: /home/wjw/.arduino15
board_manager: null

```

**Comment by OBerghmans** [comment]
Same behaviour here on my RPi 3:

Pi3:~ $ ./arduino-cli-0.3.2-alpha.preview-linuxarm core update-index
 0 / 234288 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x123d4]

goroutine 32 [running]:
sync/atomic.addUint64(0x11b86074, 0xe7f, 0x0, 0x1000, 0xe7f)
        /home/jenkins/go1.10.2-patched/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).AsyncRun(0x11b86060)
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:82 +0x17c
created by github.com/arduino/arduino-cli/vendor/go.bug.st/downloader.(*Downloader).RunAndPoll
        /home/jenkins/workspace/arduino-cli/src/github.com/arduino/arduino-cli/vendor/go.bug.st/downloader/downloader.go:61 +0x70

**Comment by OBerghmans** [comment]
This seems to work a lot better:

```
Pi3:~ $ ./arduino-cli-25-PR91-linuxarm core update-index
Updating index: package_index.json downloaded
```

Will test further later today, but this specific issue is resolved for me.

**Comment by wjwieland** [comment]
This fixes the issue on 64 bit machines.  
When might this be pushed out to the 32 bit and RPi platforms?
Thanks so much for looking into this!

**Comment by wjwieland** [comment]
I can confirm update-index for both core and lib on the linux 64 and linux ARM now work as expected. For some reason I get 404 - not found error when attempting to retrieve the Linux 32 tar.bz2 file from the code-coverage page 'Build completed' download link, so have not yet tested on my 32 bit system.

Thanks again for the work on this!

PS: this comment was mistakenly placed on the code coverage page and subsequently copied here.  Sorry for the mess...
