### ISSUE TITLE
Request for clarification arduino IDE toolchain selection

### ISSUE THREAD

**Issue by jantje** [arduino/arduino-cli#873]
From [the "package index specification"](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/):

https://github.com/arduino/arduino-cli/blob/6ac5f7a3ca3b9057931b5a75919ca708c0fb6be7/docs/package_index_json-specification.md#L166-L167

I always understood the Arduino IDE selected the tool(chain)? with the highest version number (making the assumption the latest is the one with the highest version number). However testing shows this is  not Arduino IDE behaviour.
 
For example installing the "SparkFun Apollo3 Boards" platform (https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json) means installing `arm-none-eabi-gcc\\8-2018-q4-major`
After installing the sparkfun platform, Arduino Zero compiles with `arm-none-eabi-gcc\\7-2017q4` (version 7) and not with the sparkfun tool (version 8).

Can you please specify how Arduino IDE selects the tool(chain)?

Note: IMHO the arduino framework specifies/uses platform versions and tool versions but does not specify/use toolchain versions.

**Comment by ubidefeo** [comment]
@per1234 
I saw that documentation has been made regarding this task
can we close it?

**Comment by jantje** [comment]
I read this
> {runtime.tools.TOOL_NAME.path} points to the latest version of the tool available.

which is IMHO not correct

**Comment by umbynos** [comment]
@jantje this issue should be solved by https://github.com/arduino/arduino-cli/pull/1887, can you confirm it?

**Comment by jantje** [comment]
This indeed solves the problem of lack of documentation.
However IMHO with the described strategy there will be boards that no longer compile after the change.

>     What is the new behavior?
>     In the situation above where a tool is provided by multiple packages then the compiler will pick in order of priority:
>         the tool provided by the board's package
>         in absence of it, the tool (from a 3rd party) with the greatest version according to semver
>         in case of a tie, the tool from the packager whose name comes first in alphabetic order
>         The last rule is merely a way to make the tool selection fully deterministic even in the most uncommon situation.
