### ISSUE TITLE
wind10 compile output file path Error

### ISSUE THREAD

**Issue by berry0511** [arduino/arduino-cli#90]
![image](https://user-images.githubusercontent.com/16091368/48383803-4bb72c00-e722-11e8-81a4-89bc2de53029.png)
When i compile the sketch, the output file path cannot be found.

![image](https://user-images.githubusercontent.com/16091368/48383833-6be6eb00-e722-11e8-8d7c-a50a5a968e9b.png)
In this img, the windows showed cannot create the floder because the specific floder is the same name with the sketch file "test.ino".

so I tried to change the output file path to the floder same as test.ino with command below

`arduino-cli.exe compile --fqbn arduino:avr:uno F:\arduino\cli\test\test.ino -o F:\arduino\cli\test\ --debug`

![image](https://user-images.githubusercontent.com/16091368/48384034-7fdf1c80-e723-11e8-8d55-03a9a7be1a17.png)
it works!

But, when i'm doing upload process, same question occured.
![image](https://user-images.githubusercontent.com/16091368/48384076-a604bc80-e723-11e8-9cab-882bba6aea33.png)
cannot create the path.

And the I tried to specify the upload file with command below
`arduino-cli.exe upload -p COM4 --fqbn arduino:avr:uno -i F:\arduino\cli\test\test.hex`

![image](https://user-images.githubusercontent.com/16091368/48384168-127fbb80-e724-11e8-9b9b-a5264e520ef6.png)
failed :(

so maybe we can change the default output compile file path or we can specify the upload hex file manully?

**Comment by cmaglie** [comment]
Thanks for the bug report.

> so maybe we can change the default output compile file path or we can specify the upload hex file manully?

Yes, try use `-i path` flag on upload.

**Comment by berry0511** [comment]
> Could you post the output with the `--debug` option?
> What is `F:`? I mean it's a real hard-drive or it's some sort of network storage?
> Do you have any clue why the CLI can't create the output file?

I have found the question: 
this is my cmd `arduino-cli.exe compile --fqbn arduino:avr:uno F:\arduino\cli\test\test.ino --debug`
my path points to `F:\arduino\cli\test\test.ino`, test.ino is my sketch.
and then I change the path to `F:\arduino\cli\test`, it works fine.

SO, here's my clue:
1. When executing the compile command, don't specify the sketch file,  specify the folder where the sketch file is located.
2. When I specify the sketch file, I have to use `-o` flag to change the default output file path. But in this way I can't upload the hex file.

**Comment by berry0511** [comment]
I think it's not a bug, close it
