### ISSUE TITLE
bcmi-labs arduino-modules is removed?

### ISSUE THREAD

**Issue by riisen** [arduino/arduino-cli#98]
`$ go get -u github.com/arduino/arduino-cli
cd .; git clone https://github.com/bcmi-labs/arduino-modules /home/udooer/golang/arduino/src/github.com/bcmi-labs/arduino-modules
Cloning into '/home/udooer/golang/arduino/src/github.com/bcmi-labs/arduino-modules'...
remote: Repository not found.
fatal: repository 'https://github.com/bcmi-labs/arduino-modules/' not found`

**Comment by cmaglie** [comment]
Right, BTW we use a very small part of that, I'm going to inline the relevant part and remove all the rest.
